### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by sinelaw** [gcovr/gcovr#206]
Running on Ubuntu 17.10 with Python 2.7.14 and GCC 7.2.0
On master (acc9faf1dd84c), I run `nosetests -v` and get:
```
======================================================================
FAIL: function test: test_simple1 (test_gcovr.GcovrTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 345, in <lambda>
    func = lambda self, c1=fn, c2=name, c3=suite: _run_fn_test(self, c1, c2, c3)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 216, in _run_fn_test
    explanation = fn(self, name)
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 105, in gcovr_test_txt
    self.assertFileEqualsBaseline("coverage.txt", "reference/coverage.txt")
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 311, in assertFileEqualsBaseline
    baseline + "\nDiffs:\n" + diffs)
AssertionError: Unexpected output difference at line 7:
   testfile=coverage.txt
   baseline=reference/coverage.txt
Diffs:
--- reference/coverage.txt

+++ coverage.txt

@@ -1,6 +1,6 @@

 File                                       Lines    Exec  Cover   Missing
 ------------------------------------------------------------------------------
-main.cpp                                      10       8    80%   6,22
+main.cpp                                      10       8    80%   6,19
 ------------------------------------------------------------------------------
 TOTAL                                         10       8    80%
 ------------------------------------------------------------------------------

-------------------- >> begin captured stdout << ---------------------
STDOUT - START
rm -f testcase
rm -f *.gc*
rm -f coverage.txt coverage.xml coverage*.html
STDOUT - END
STDOUT - START
g++ -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase
STDOUT - END
STDOUT - START
./testcase
../../../scripts/gcovr --fail-under-line 80.1; test $? -eq 2
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
main.cpp                                      10       8    80%   6,19
------------------------------------------------------------------------------
TOTAL                                         10       8    80%
------------------------------------------------------------------------------
../../../scripts/gcovr --fail-under-branch 50.1; test $? -eq 4
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
main.cpp                                      10       8    80%   6,19
------------------------------------------------------------------------------
TOTAL                                         10       8    80%
------------------------------------------------------------------------------
../../../scripts/gcovr --fail-under-line 80.1 --fail-under-branch 50.1; test $? -eq 6
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
main.cpp                                      10       8    80%   6,19
------------------------------------------------------------------------------
TOTAL                                         10       8    80%
------------------------------------------------------------------------------
../../../scripts/gcovr --fail-under-line 79.9 --fail-under-branch 49.9
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
main.cpp                                      10       8    80%   6,19
------------------------------------------------------------------------------
TOTAL                                         10       8    80%
------------------------------------------------------------------------------
../../../scripts/gcovr -d -o coverage.txt
STDOUT - END

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: function test: test_use-existing (test_gcovr.GcovrTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 345, in <lambda>
    func = lambda self, c1=fn, c2=name, c3=suite: _run_fn_test(self, c1, c2, c3)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 216, in _run_fn_test
    explanation = fn(self, name)
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 105, in gcovr_test_txt
    self.assertFileEqualsBaseline("coverage.txt", "reference/coverage.txt")
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 311, in assertFileEqualsBaseline
    baseline + "\nDiffs:\n" + diffs)
AssertionError: Unexpected output difference at line 7:
   testfile=coverage.txt
   baseline=reference/coverage.txt
Diffs:
--- reference/coverage.txt

+++ coverage.txt

@@ -1,6 +1,6 @@

 File                                       Lines    Exec  Cover   Missing
 ------------------------------------------------------------------------------
-main.cpp                                      10       8    80%   6,22
+main.cpp                                      10       8    80%   6,19
 ------------------------------------------------------------------------------
 TOTAL                                         10       8    80%
 ------------------------------------------------------------------------------

-------------------- >> begin captured stdout << ---------------------
STDOUT - START
rm -f testcase
rm -f *.gc*
rm -f coverage.txt coverage.xml coverage*.html
STDOUT - END
STDOUT - START
g++ -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase
STDOUT - END
STDOUT - START
./testcase
gcov *.gcda --branch-counts --branch-probabilities --preserve-paths
File 'main.cpp'
Lines executed:80.00% of 10
Branches executed:100.00% of 8
Taken at least once:50.00% of 8
Calls executed:66.67% of 3
Creating 'main.cpp.gcov'

File '/usr/include/c++/7/iostream'
Lines executed:100.00% of 1
No branches
Calls executed:100.00% of 2
Creating '#usr#include#c++#7#iostream.gcov'

../../../scripts/gcovr -v -g -d -o coverage.txt
Scanning directory . for gcov files...
Found 2 files (and will process 2)
Finding source file corresponding to a gcov data file
  currdir      /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing
  gcov_fname   /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing/#usr#include#c++#7#iostream.gcov
               ['        -', '    0', 'Source', '/usr/include/c++/7/iostream\n']
  source_fname None
  root         /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing
  fname        /usr/include/c++/7/iostream
Parsing coverage data for file /usr/include/c++/7/iostream
  Filtering coverage data for file /usr/include/c++/7/iostream
Finding source file corresponding to a gcov data file
  currdir      /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing
  gcov_fname   /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing/main.cpp.gcov
               ['        -', '    0', 'Source', 'main.cpp\n']
  source_fname None
  root         /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing
  fname        /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing/main.cpp
Parsing coverage data for file /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing/main.cpp
uncovered set([19, 6])
covered {4: 1, 5: 1, 8: 1, 13: 1, 14: 1, 18: 1, 25: 1, 26: 3}
branches {18: {0: 0, 1: 1}, 26: {1: 1, 2: 0, 3: 1, 4: 0}, 5: {0: 0, 1: 1}}
noncode set([2, 3, 9, 10, 11, 12, 23, 24])
Gathered coveraged data for 1 files
STDOUT - END

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: function test: test_wspace (test_gcovr.GcovrTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 345, in <lambda>
    func = lambda self, c1=fn, c2=name, c3=suite: _run_fn_test(self, c1, c2, c3)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 216, in _run_fn_test
    explanation = fn(self, name)
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 105, in gcovr_test_txt
    self.assertFileEqualsBaseline("coverage.txt", "reference/coverage.txt")
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 311, in assertFileEqualsBaseline
    baseline + "\nDiffs:\n" + diffs)
AssertionError: Unexpected output difference at line 7:
   testfile=coverage.txt
   baseline=reference/coverage.txt
Diffs:
--- reference/coverage.txt

+++ coverage.txt

@@ -1,6 +1,6 @@

 File                                       Lines    Exec  Cover   Missing
 ------------------------------------------------------------------------------
-main.cpp                                      10       8    80%   6,22
+main.cpp                                      10       8    80%   6,19
 ------------------------------------------------------------------------------
 TOTAL                                         10       8    80%
 ------------------------------------------------------------------------------

-------------------- >> begin captured stdout << ---------------------
STDOUT - START
rm -f */testcase
rm -f */*.gc*
rm -f coverage.txt coverage.xml coverage*.html
STDOUT - END
STDOUT - START
cd 'src code'; g++ -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase
STDOUT - END
STDOUT - START
cd 'src code'; ./testcase
../../../scripts/gcovr -r 'src code' -d -o coverage.txt
STDOUT - END

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: function test: test_simple1 (test_gcovr.GcovrXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 345, in <lambda>
    func = lambda self, c1=fn, c2=name, c3=suite: _run_fn_test(self, c1, c2, c3)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 216, in _run_fn_test
    explanation = fn(self, name)
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 116, in gcovr_test_xml
    self.compare_xml()
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 47, in compare_xml
    self.assertMatchesXmlBaseline(coverage, reference, tolerance=1e-4, exact=True)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 261, in assertMatchesXmlBaseline
    err))
AssertionError: XML testfile does not match the baseline:
   testfile=coverage.xml
   baseline=reference/coverage.xml
(<root>.coverage.packages.package.classes.class.lines.line) Could not find item 5 in output list:
baseline:
[OrderedDict([(u'@hits', 1), (u'@number', 4), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 5), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 6), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 8), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 13), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 17), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 18), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 22), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 25), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 3), (u'@condition-coverage', u'50% (2/4)'), (u'@number', 26), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))])]
output:
[OrderedDict([(u'@hits', 1), (u'@number', 4), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 5), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 6), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 8), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 13), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 14), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 18), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 19), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 25), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 3), (u'@condition-coverage', u'50% (2/4)'), (u'@number', 26), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))])]
ERROR: (<root>.coverage.packages.package.classes.class.lines.line[9]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']
-------------------- >> begin captured stdout << ---------------------
STDOUT - START
rm -f testcase
rm -f *.gc*
rm -f coverage.txt coverage.xml coverage*.html
STDOUT - END
STDOUT - START
g++ -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase
STDOUT - END
STDOUT - START
./testcase
../../../scripts/gcovr -d -x -o coverage.xml
STDOUT - END
(<root>.coverage.packages.package.classes.class.lines.line[5].@number) Values differ:
baseline:
17
output:
14
(<root>.coverage.packages.package.classes.class.lines.line[6]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']
(<root>.coverage.packages.package.classes.class.lines.line[7].@hits) Values differ:
baseline:
1
output:
0
(<root>.coverage.packages.package.classes.class.lines.line[8].@number) Values differ:
baseline:
17
output:
25
(<root>.coverage.packages.package.classes.class.lines.line[9]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: function test: test_use-existing (test_gcovr.GcovrXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 345, in <lambda>
    func = lambda self, c1=fn, c2=name, c3=suite: _run_fn_test(self, c1, c2, c3)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 216, in _run_fn_test
    explanation = fn(self, name)
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 116, in gcovr_test_xml
    self.compare_xml()
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 47, in compare_xml
    self.assertMatchesXmlBaseline(coverage, reference, tolerance=1e-4, exact=True)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 261, in assertMatchesXmlBaseline
    err))
AssertionError: XML testfile does not match the baseline:
   testfile=coverage.xml
   baseline=reference/coverage.xml
(<root>.coverage.packages.package.classes.class.lines.line) Could not find item 5 in output list:
baseline:
[OrderedDict([(u'@hits', 1), (u'@number', 4), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 5), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 6), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 8), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 13), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 17), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 18), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 22), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 25), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 3), (u'@condition-coverage', u'50% (2/4)'), (u'@number', 26), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))])]
output:
[OrderedDict([(u'@hits', 1), (u'@number', 4), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 5), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 6), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 8), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 13), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 14), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 18), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 19), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 25), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 3), (u'@condition-coverage', u'50% (2/4)'), (u'@number', 26), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))])]
ERROR: (<root>.coverage.packages.package.classes.class.lines.line[9]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']
-------------------- >> begin captured stdout << ---------------------
STDOUT - START
rm -f testcase
rm -f *.gc*
rm -f coverage.txt coverage.xml coverage*.html
STDOUT - END
STDOUT - START
g++ -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase
STDOUT - END
STDOUT - START
./testcase
gcov *.gcda --branch-counts --branch-probabilities --preserve-paths
File 'main.cpp'
Lines executed:80.00% of 10
Branches executed:100.00% of 8
Taken at least once:50.00% of 8
Calls executed:66.67% of 3
Creating 'main.cpp.gcov'

File '/usr/include/c++/7/iostream'
Lines executed:100.00% of 1
No branches
Calls executed:100.00% of 2
Creating '#usr#include#c++#7#iostream.gcov'

../../../scripts/gcovr -v -g -d -x -o coverage.xml
Scanning directory . for gcov files...
Found 2 files (and will process 2)
Finding source file corresponding to a gcov data file
  currdir      /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing
  gcov_fname   /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing/#usr#include#c++#7#iostream.gcov
               ['        -', '    0', 'Source', '/usr/include/c++/7/iostream\n']
  source_fname None
  root         /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing
  fname        /usr/include/c++/7/iostream
Parsing coverage data for file /usr/include/c++/7/iostream
  Filtering coverage data for file /usr/include/c++/7/iostream
Finding source file corresponding to a gcov data file
  currdir      /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing
  gcov_fname   /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing/main.cpp.gcov
               ['        -', '    0', 'Source', 'main.cpp\n']
  source_fname None
  root         /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing
  fname        /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing/main.cpp
Parsing coverage data for file /home/noam/repos/thirdparty/gcovr/gcovr/tests/use-existing/main.cpp
uncovered set([19, 6])
covered {4: 1, 5: 1, 8: 1, 13: 1, 14: 1, 18: 1, 25: 1, 26: 3}
branches {18: {0: 0, 1: 1}, 26: {1: 1, 2: 0, 3: 1, 4: 0}, 5: {0: 0, 1: 1}}
noncode set([2, 3, 9, 10, 11, 12, 23, 24])
Gathered coveraged data for 1 files
STDOUT - END
(<root>.coverage.packages.package.classes.class.lines.line[5].@number) Values differ:
baseline:
17
output:
14
(<root>.coverage.packages.package.classes.class.lines.line[6]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']
(<root>.coverage.packages.package.classes.class.lines.line[7].@hits) Values differ:
baseline:
1
output:
0
(<root>.coverage.packages.package.classes.class.lines.line[8].@number) Values differ:
baseline:
17
output:
25
(<root>.coverage.packages.package.classes.class.lines.line[9]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: function test: test_wspace (test_gcovr.GcovrXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 345, in <lambda>
    func = lambda self, c1=fn, c2=name, c3=suite: _run_fn_test(self, c1, c2, c3)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 216, in _run_fn_test
    explanation = fn(self, name)
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 116, in gcovr_test_xml
    self.compare_xml()
  File "/home/noam/repos/thirdparty/gcovr/gcovr/tests/test_gcovr.py", line 47, in compare_xml
    self.assertMatchesXmlBaseline(coverage, reference, tolerance=1e-4, exact=True)
  File "/home/noam/.local/lib/python2.7/site-packages/pyutilib/th/pyunit.py", line 261, in assertMatchesXmlBaseline
    err))
AssertionError: XML testfile does not match the baseline:
   testfile=coverage.xml
   baseline=reference/coverage.xml
(<root>.coverage.packages.package.classes.class.lines.line) Could not find item 5 in output list:
baseline:
[OrderedDict([(u'@hits', 1), (u'@number', 4), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 5), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 6), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 8), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 13), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 17), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 18), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 22), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 25), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 3), (u'@condition-coverage', u'50% (2/4)'), (u'@number', 26), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))])]
output:
[OrderedDict([(u'@hits', 1), (u'@number', 4), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 5), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 6), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 8), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 13), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 14), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@condition-coverage', u'50% (1/2)'), (u'@number', 18), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))]),
 OrderedDict([(u'@hits', 0), (u'@number', 19), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 1), (u'@number', 25), (u'@branch', u'false')]),
 OrderedDict([(u'@hits', 3), (u'@condition-coverage', u'50% (2/4)'), (u'@number', 26), (u'@branch', u'true'), (u'conditions', OrderedDict([(u'condition', OrderedDict([(u'@type', u'jump'), (u'@number', 0), (u'@coverage', u'50%')]))]))])]
ERROR: (<root>.coverage.packages.package.classes.class.lines.line[9]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']
-------------------- >> begin captured stdout << ---------------------
STDOUT - START
rm -f */testcase
rm -f */*.gc*
rm -f coverage.txt coverage.xml coverage*.html
STDOUT - END
STDOUT - START
cd 'src code'; g++ -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase
STDOUT - END
STDOUT - START
cd 'src code'; ./testcase
../../../scripts/gcovr -r 'src code' -d -x -o coverage.xml
STDOUT - END
(<root>.coverage.packages.package.classes.class.lines.line[5].@number) Values differ:
baseline:
17
output:
14
(<root>.coverage.packages.package.classes.class.lines.line[6]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']
(<root>.coverage.packages.package.classes.class.lines.line[7].@hits) Values differ:
baseline:
1
output:
0
(<root>.coverage.packages.package.classes.class.lines.line[8].@number) Values differ:
baseline:
17
output:
25
(<root>.coverage.packages.package.classes.class.lines.line[9]) Baseline and output have different keys:
baseline:
[u'@hits', u'@number', u'@branch']
output:
[u'@hits', u'@condition-coverage', u'@number', u'@branch', u'conditions']

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 57 tests in 30.703s

FAILED (failures=6)
```

**Comment by sinelaw** [comment]
The problem goes away if I use an older version of GCC (e.g. 4.8). The newer GCC produces slightly different coverage output for function calls that span multiple lines, reporting the starting line of a function call instead of the last, i.e.

```
     // this line is not covered (branch not reached)
     foo(    // <-- this line is reported by GCC 7.2.0 as not covered
        1
        )
        ;      // <-- this line is reported by GCC 4.8.3 as not covered
```

**Comment by sinelaw** [comment]
...so the question is, what is the value of a test the spreads an expression over multiple lines? I'm guessing it was added to counter some bug? We can make the tests less sensitive to compiler differences if we avoid spreading the expression over multiple lines.

**Comment by latk** [comment]
This is more or less a known problem, but it's good to have a central issue to discuss this. Different GCC versions differ subtly in which lines they consider to be covered. On Travis CI and Appveyor, we sidestep these issues by only testing with GCC 5.x. I don't know a good way to avoid these problems, but some resolution is necessary so that we can test multiple GCC versions and Clang versions on Travis (see also #134 and #179).

The weird multi-line test is necessary to assert that the uncovered statement is only counted as one uncovered line, even if it is spread over multiple lines. I think this also ties into the detection of code lines (if a line only includes parens, braces, or semicolons it sometimes gets excluded?). Since this “simple” test was one of the first test cases, it has been widely copied into unrelated test cases.

As a first step, this formatting can be removed from unrelated tests, thus limiting the problem. But we still have to figure out how to deal with legitimate compiler differences.

 - different reference files for different compilers? If so, how is the correct set of reference files selected? How can we make sure they are all exercised and kept up to date?
 - test-case specific data scrubbing to remove these differences? How can that be integrated into the existing test workflow? How can this be implemented without potentially hiding bugs?

**Comment by latk** [comment]
I think the next step for this issue is to add extra compilers to the Travis CI build, but allow them to fail. That way, we'll get automated reports about which tests are broken, and can easily see when they are fixed.

This requires a more complicated `matrix` setup in the .travis.yml file so that different compilers can be installed with the APT addon. We don't need all compiler × Python combinations, but can e.g. only test additional compilers with Python 3.5. I've used a similar setup in a Perl project of mine, maybe we can [borrow from there](https://github.com/latk/p5-Async-Trampoline/blob/master/.travis.yml).

**Comment by Spacetown** [comment]
What about changing the function:
https://github.com/gcovr/gcovr/blob/39f5a82fb742300ea09adffa8f70b96a17f79061/gcovr/tests/test_gcovr.py#L92-L96

Checking a list of reference directories and use the first existing directory as reference:
- reference.gccx.osy
- reference.gccx
- reference.osy
- reference

**Comment by Spacetown** [comment]
The matrix is already included and all test are working.
