### ISSUE TITLE
UnicodeDecodeError when running gcovr with meson

### ISSUE THREAD

**Issue by robinmoussu** [gcovr/gcovr#292]
Hello,
I'm trying to generate code coverage on my pet project using meson build system. I think the issue comes from gcovr, but I'm not totally sure.

It may be the same issue that #166

To sum-up, I get the following error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 108: invalid start byte
```

It may be a locale related error. I tried to re-build + re-run gcov after doing `export LANG=C`, or by modifying /usr/lib/python3.7/site-packages/gcovr/gcov.py to LC_ALL='C' (as someone did in #166), but it didn't fixed it.

I tried to include anything possible, but feel free to ask me more details.

```
➜  $ locale
LANG=fr_FR.UTF-8
LC_CTYPE=fr_FR.UTF-8
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
➜  $ locale -a
C
en_US.utf8
fr_FR.utf8
POSIX
➜  $ uname -a
Linux scha 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux
```

Step to reproduce:

```
➜  $ git clone https://github.com/tiernemi/meson-sample-project.git && cd meson-sample-project.git
➜  $ mkdir build && cd build
➜  $ meson  -Db_coverage=true ..
The Meson build system
Version: 0.49.0
Source dir: /home/robin/dev/meson-sample-project
Build dir: /home/robin/dev/meson-sample-project/build
Build type: native build
Project name: sample_cpp_project
Project version: 1.0
Native C++ compiler: ccache c++ (gcc 9.0.0 "c++ (GCC) 9.0.0 20190107 (experimental)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring config.h using configuration
Library fizz found: YES
Found pkg-config: /usr/bin/pkg-config (1.6.0)
Dependency GTest found: YES 1.8.1
Dependency threads found: YES
Dependency benchmark found: YES 1.4.1
Dependency threads found: YES (cached)
Configuring Doxyfile using configuration
Program doxygen found: YES (/usr/bin/doxygen)
Configuring .clang-format using configuration
meson.build:51: WARNING: Got an empty configuration_data() object and found no substitutions in the input file '.clang-format'. If you want to copy a file to the build dir, use the 'copy:' keyword argument added in 0.47.0
Configuring .clang-tidy using configuration
meson.build:61: WARNING: Got an empty configuration_data() object and found no substitutions in the input file '.clang-tidy'. If you want to copy a file to the build dir, use the 'copy:' keyword argument added in 0.47.0
Build targets in project: 13
Found ninja-1.8.2 at /usr/bin/ninja
➜  $ ninja
[24/24] Linking target benchmarks/all_benchmarks.
➜  $ ninja test
[0/1] Running all tests.
1/2 foo test                                OK       0.04 s
2/2 bar test                                OK       0.04 s

Ok:                    2
Expected Fail:         0
Fail:                  0
Unexpected Pass:       0
Skipped:               0
Timeout:               0

Full log written to /home/robin/dev/meson-sample-project/build/meson-logs/testlog.txt
➜  $ ninja coverage-text
[1/1] Generates text coverage report.
FAILED: meson-coverage-text
/usr/bin/meson --internal coverage --text /home/robin/dev/meson-sample-project /home/robin/dev/meson-sample-project/subprojects /home/robin/dev/meson-sample-project/build /home/robin/dev/meson-sample-project/build/meson-logs
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 71, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 656, in run_gcov_and_process_files
    out = out.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 1346: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 71, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 656, in run_gcov_and_process_files
    out = out.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 1346: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 11, in <module>
    load_entry_point('gcovr==4.1', 'console_scripts', 'gcovr')()
  File "/usr/lib/python3.7/site-packages/gcovr/__main__.py", line 562, in main
    contexts = pool.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 160, in __exit__
    self.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 151, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3.7/site-packages/gcovr/__main__.py", line 562, in main
    contexts = pool.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 151, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 71, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 656, in run_gcov_and_process_files
    out = out.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 1346: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.49.0', 'console_scripts', 'meson')()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 192, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 181, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 145, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/coverage.py", line 149, in run
    options.log_dir)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/coverage.py", line 49, in coverage
    '-o', os.path.join(log_dir, 'coverage.txt'),
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcovr', '-r', '/home/robin/dev/meson-sample-project/build', '-e', '/home/robin/dev/meson-sample-project/subprojects', '-o', '/home/robin/dev/meson-sample-project/build/meson-logs/coverage.txt']' returned non-zero exit status 1.
ninja: build stopped: subcommand failed.
```

---

If I try to to re-run the gcovr command with `-v`, I get the same error:

```
➜  $ gcovr -v -r /home/robin/dev/meson-sample-project/build -e /home/robin/dev/meson-sample-project/subprojects -o /home/robin/dev/meson-sample-project/build/meson-logs/coverage.txt
# lots of output
Running gcov: 'gcov /home/robin/dev/meson-sample-project/build/src/foo/1c916c5@@foo@sta/foo.cc.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory /home/robin/dev/meson-sample-project/build/src/foo/1c916c5@@foo@sta' in '/tmp/tmpxpkiucu2'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 71, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 658, in run_gcov_and_process_files
    out = out.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 86: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 71, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 658, in run_gcov_and_process_files
    out = out.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 86: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 11, in <module>
    load_entry_point('gcovr==4.1', 'console_scripts', 'gcovr')()
  File "/usr/lib/python3.7/site-packages/gcovr/__main__.py", line 562, in main
    contexts = pool.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 160, in __exit__
    self.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 151, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3.7/site-packages/gcovr/__main__.py", line 562, in main
    contexts = pool.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 151, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 71, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 658, in run_gcov_and_process_files
    out = out.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 86: invalid start byte
```

I am not sure if the type of the gcda type should be binary:

```
➜  $ file -bi  /home/robin/dev/meson-sample-project/build/src/foo/1c916c5@@foo@sta/foo.cc.gcda
application/octet-stream; charset=binary
```

**Comment by latk** [comment]
This problem is not directly related to locales. The problem is that gcovr treats input as text, not as arbitrary binary data. So gcovr tries to parse the stdout of gcov as UTF-8 text. However, gcov (as many C programs) is encoding-agnostic. It just prints out some bytes. Here, it seems like gcov echoes some text that it got elsewhere, for example a filename that isn't valid UTF-8.

To debug this problem, please apply the following diff to `gcovr/gcov.py` near line 650, and provide the output of the error message (detailed build logs not required):

``` diff
     with locked_directory(chdir):
         out, err = subprocess.Popen(
             cmd, env=env, cwd=chdir,
             stdout=subprocess.PIPE,
             stderr=subprocess.PIPE).communicate()
-        out = out.decode('utf-8')
-        err = err.decode('utf-8')
+        try:
+          out = out.decode('utf-8')
+        except UnicodeDecodeError:
+          raise RuntimeError("could not decode out as UTF-8: {!r}".format(out))
+        try:
+          err = err.decode('utf-8')
+        except UnicodeDecodeError:
+          raise RuntimeError("could not decode err as UTF-8: {!r}".format(err))
 
         # find the files that gcov created
```

My bet is that something that isn't gcov is invoked in place of gcov, thus producing gibberish output.

And yes, .gcda is a binary format. This is the raw coverage files containing the per-statement counters that an instrumented process writes during execution. The gcov tools parses these into textual formats that gcovr can process.

**Comment by robinmoussu** [comment]
Thanks for the quick answer :)

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 659, in run_gcov_and_process_files
    out = out.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 88: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gcovr", line 11, in <module>
    load_entry_point('gcovr==4.1', 'console_scripts', 'gcovr')()
  File "/usr/lib/python3.7/site-packages/gcovr/__main__.py", line 562, in main
    contexts = pool.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 160, in __exit__
    self.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 151, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3.7/site-packages/gcovr/__main__.py", line 562, in main
    contexts = pool.wait()
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 151, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3.7/site-packages/gcovr/workers.py", line 71, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "/usr/lib/python3.7/site-packages/gcovr/gcov.py", line 661, in run_gcov_and_process_files
    raise RuntimeError("could not decode out as UTF-8: {!r}".format(out))
RuntimeError: could not decode out as UTF-8: b"File '../src/foo/foo.cc'\nLines executed:100.00% of 1\nNo branches\nNo calls\nCreating ' pn+\x89\x7f'\n\nFile '/usr/include/c++/9.0.0/iostream'\nNo executable lines\nNo branches\nNo calls\nRemoving ''\n\n"
Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.49.0', 'console_scripts', 'meson')()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 192, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 181, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 145, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/coverage.py", line 149, in run
    options.log_dir)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/coverage.py", line 49, in coverage
    '-o', os.path.join(log_dir, 'coverage.txt'),
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcovr', '-r', '/home/robin/dev/meson-sample-project/build', '-e', '/home/robin/dev/meson-sample-project/subprojects', '-o', '/home/robin/dev/meson-sample-project/build/meson-logs/coverage.txt']' returned non-zero exit status 1.
ninja: build stopped: subcommand failed.
```

```
➜  $ file -bi ../src/foo/foo.cc
text/x-c; charset=us-ascii
```

**Comment by robinmoussu** [comment]
Maybe my gcov is too recent?

```
➜  $ gcov --version
gcov (GCC) 9.0.0 20190107 (experimental)
```

**Comment by robinmoussu** [comment]
Notice the difference with and without the `LANG=C` (by default, I have `LANG=fr_FR.UTF-8`)
```
➜  $ gcov /home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta/baz.cc.gcno --branch-counts --branch-probabilities --preserve-paths --object-directory /home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta
/home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta/baz.cc.gcda: ne peut ouvrir le fichier de données, supposé non exécuté
File « ../third_party/src/baz/baz.cc »
Lignes exécutées: 0.00% sur 1
Pas de branchement
Pas d'appel
Impossible d'ouvrir le fichier de sortie «  »

File « /usr/include/c++/9.0.0/iostream »
Aucune ligne exécutable
Pas de branchement
Pas d'appel
Suppression de «  »
```
```
➜  $ LANG=C gcov /home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta/baz.cc.gcno --branch-counts --branch-probabilities --preserve-paths --object-directory /home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta
/home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta/baz.cc.gcda:cannot open data file, assuming not executed
File '../third_party/src/baz/baz.cc'
Lines executed:0.00% of 1
No branches
No calls
Creating '@�ٮ'
Cannot open source file ../third_party/src/baz/baz.cc

File '/usr/include/c++/9.0.0/iostream'
No executable lines
No branches
No calls
Removing '�ٮ'
```
And just in case:
```
➜  $ file -bi /home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta/baz.cc.gcno
application/octet-stream; charset=binary
➜  $ file -bi  /home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta
inode/directory; charset=binary
```
```
➜  ls -l /home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta/baz.cc.gcda
ls: cannot access '/home/robin/dev/meson-sample-project/build/third_party/src/baz/6798489@@baz@sta/baz.cc.gcda': No such file or directory
➜  $ ls -l third_party/src/baz/6798489@@baz@sta/baz.cc.*
-rw-r--r-- 1 robin robin 708 22 janv. 19:58 third_party/src/baz/6798489@@baz@sta/baz.cc.gcno
-rw-r--r-- 1 robin robin 28K 22 janv. 19:58 third_party/src/baz/6798489@@baz@sta/baz.cc.o
```

**Comment by latk** [comment]
Ok, that is weird but clearly an upstream problem in GCC/gcov. Please report it there. But thank you very much for digging into this!

**Comment by robinmoussu** [comment]
I will do it. Thanks for the help.
