### ISSUE TITLE
Windows absolute paths are garbled when passed to shutil

### ISSUE THREAD

**Issue by tuze-kuyucu** [gcovr/gcovr#313]
Relative paths seem to work fine i.e. `gcovr -r .` but giving the absolute path to a repo ends up in the exception below:
```
c:\code\cc13xx_firmware\build_host>python -m gcovr -r C:/code/cc13xx_firmware
Traceback (most recent call last):
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\workers.py", line 71, in worker
    work(*args, **kwargs)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 666, in run_gcov_and_process_files
    tempdir=tempdir)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 711, in select_gcov_files_from_stdout
    shutil.copyfile(full, active_files[-1])
  File "C:\Anaconda3\envs\dt_python3\lib\shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\#home#tuze#repos#cc13xx_firmware#dt_mcu_lib#drivers_cc13xx#dt_nvm#src#dt_nvm_counter.c.gcov'
Traceback (most recent call last):
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\workers.py", line 71, in worker
    work(*args, **kwargs)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 666, in run_gcov_and_process_files
    tempdir=tempdir)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 711, in select_gcov_files_from_stdout
    shutil.copyfile(full, active_files[-1])
  File "C:\Anaconda3\envs\dt_python3\lib\shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\#home#tuze#repos#cc13xx_firmware#dt_mcu_lib#drivers_cc13xx#dt_nvm#src#dt_nvm_counter.c.gcov'
Traceback (most recent call last):
  File "C:\Anaconda3\envs\dt_python3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\dt_python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\__main__.py", line 600, in <module>
    main()
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\__main__.py", line 562, in main
    contexts = pool.wait()
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\workers.py", line 160, in __exit__
    self.wait()
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\workers.py", line 151, in wait
    raise self.exceptions[0][1]
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\__main__.py", line 562, in main
    contexts = pool.wait()
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\workers.py", line 151, in wait
    raise self.exceptions[0][1]
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\workers.py", line 71, in worker
    work(*args, **kwargs)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 564, in process_datafile
    options=options, logger=logger, toerase=toerase, errors=errors, chdir=dir_, tempdir=workdir)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 666, in run_gcov_and_process_files
    tempdir=tempdir)
  File "C:\Anaconda3\envs\dt_python3\lib\site-packages\gcovr\gcov.py", line 711, in select_gcov_files_from_stdout
    shutil.copyfile(full, active_files[-1])
  File "C:\Anaconda3\envs\dt_python3\lib\shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\#home#tuze#repos#cc13xx_firmware#dt_mcu_lib#drivers_cc13xx#dt_nvm#src#dt_nvm_counter.c.gcov'

```

**Comment by latk** [comment]
Interesting. Which version of gcovr are you using? Could you run  gcovr in `--verbose` mode?

**Comment by tuze-kuyucu** [comment]
Hi, 
It seems that I had some unix files in another build directory that the absolute path run kept picking up so this reported issue is invalid.

Absolute paths still do not work for me though. Here is an excerpt from gcovr with verbose on:

`c:\code\cc13xx_firmware\build_host>python -m gcovr -r . --verbose`

```
Filters for --root: (1)
- re.compile('c\\:\\\\code\\\\cc13xx_firmware\\\\build_host\\\\')
Filters for --filter: (1)
- DirectoryPrefixFilter(c\:\/code\/cc13xx_firmware\/build_host\/)
Filters for --exclude: (0)
Filters for --gcov-filter: (1)
- AlwaysMatchFilter()
Filters for --gcov-exclude: (0)
Filters for --exclude-directories: (0)
Scanning directory . for gcda/gcno files...
Found 692 files (and will process 349)
Pool started with 1 threads
Processing file: c:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_integration.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda
Running gcov: 'gcov c:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_integration.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory c:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_integration.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src' in 'C:\Users\TUZE~1.KUY\AppData\Local\Temp\tmpkmv8ytnt'
Running gcov: 'gcov c:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_integration.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory c:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_integration.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src' in 'c:\code\cc13xx_firmware\build_host'
Finding source file corresponding to a gcov data file
  currdir      c:\code\cc13xx_firmware\build_host
  gcov_fname   C:\Users\TUZE~1.KUY\AppData\Local\Temp\tmpkmv8ytnt\^#dt_mcu_lib#drivers_cc13xx#sds#sds_streaming_receiver#src#bitvec.c.gcov
               ['        -', '    0', 'Source', '../dt_mcu_lib/drivers_cc13xx/sds/sds_streaming_receiver/src/bitvec.c\n']
  source_fname c:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_integration.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda
  root         c:\code\cc13xx_firmware\build_host
  fname        c:\code\cc13xx_firmware\build_host\..\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c
Parsing coverage data for file c:\code\cc13xx_firmware\build_host\..\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c
uncovered: {129, 34, 35, 74, 53, 90, 93, 127}
covered:   {67: 41, 68: 41, 69: 41, 70: 41, 71: 41, 72: 41, 88: 72, 21: 2, 22: 2, 23: 2, 24: 2, 89: 72, 92: 72, 95: 72, 96: 72, 98: 1, 99: 1, 100: 1, 103: 71, 104: 11, 106: 60, 46: 40, 47: 40, 48: 40, 49: 40, 50: 40, 51: 40, 25: 2, 117: 73, 119: 73, 120: 73, 121: 73, 122: 73, 123: 73, 124: 73, 125: 73}
branches:  {96: {0: 72, 1: 0, 2: 12, 3: 60, 4: 1, 5: 11}, 124: {0: 73, 1: 0}, 99: {0: 1, 1: 0, 2: 1, 3: 0}, 68: {0: 41, 1: 0}, 103: {0: 60, 1: 11, 2: 11, 3: 49}, 120: {0: 73, 1: 0}, 89: {0: 0, 1: 72}, 92: {0: 0, 1: 72}, 47: {0: 40, 1: 0}}
noncode:   {128, 130, 3, 5, 26, 36, 37, 54, 55, 56, 57, 75, 76, 77, 78, 91, 94, 97, 101, 102, 105, 107, 108, 118, 126}
Finding source file corresponding to a gcov data file
  currdir      c:\code\cc13xx_firmware\build_host
  gcov_fname   C:\Users\TUZE~1.KUY\AppData\Local\Temp\tmpkmv8ytnt\^#dt_mcu_lib#kernel#dt_common#inc#dt_common.h.gcov
               ['        -', '    0', 'Source', '../dt_mcu_lib/kernel/dt_common/inc/dt_common.h\n']
  source_fname c:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_integration.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda
  root         c:\code\cc13xx_firmware\build_host
  fname        c:\code\cc13xx_firmware\build_host\..\dt_mcu_lib\kernel\dt_common\inc\dt_common.h
```

`c:\code\cc13xx_firmware\build_host>python -m gcovr -r C:/code/cc13xx_firmware/build_host --verbose`

```
Filters for --root: (1)
- re.compile('C\\:\\\\code\\\\cc13xx_firmware\\\\build_host\\\\')
Filters for --filter: (1)
- DirectoryPrefixFilter(C\:\/code\/cc13xx_firmware\/build_host\/)
Filters for --exclude: (0)
Filters for --gcov-filter: (1)
- AlwaysMatchFilter()
Filters for --gcov-exclude: (0)
Filters for --exclude-directories: (0)
Scanning directory C:/code/cc13xx_firmware/build_host for gcda/gcno files...
Found 692 files (and will process 349)
Pool started with 1 threads
Processing file: C:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_map.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda
Running gcov: 'gcov C:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_map.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_map.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src' in 'C:\Users\TUZE~1.KUY\AppData\Local\Temp\tmp2dpph2mn'
Running gcov: 'gcov C:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_map.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_map.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src' in 'C:\code\cc13xx_firmware\build_host'
Finding source file corresponding to a gcov data file
  currdir      c:\code\cc13xx_firmware\build_host
  gcov_fname   C:\Users\TUZE~1.KUY\AppData\Local\Temp\tmp2dpph2mn\^#dt_mcu_lib#drivers_cc13xx#sds#sds_streaming_receiver#src#bitvec.c.gcov
               ['        -', '    0', 'Source', '../dt_mcu_lib/drivers_cc13xx/sds/sds_streaming_receiver/src/bitvec.c\n']
  source_fname C:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_map.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda
  root         C:\code\cc13xx_firmware\build_host
  fname        c:\code\cc13xx_firmware\build_host\..\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c
Parsing coverage data for file c:\code\cc13xx_firmware\build_host\..\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c
  Filtering coverage data for file c:\code\cc13xx_firmware\build_host\..\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c
Finding source file corresponding to a gcov data file
  currdir      c:\code\cc13xx_firmware\build_host
  gcov_fname   C:\Users\TUZE~1.KUY\AppData\Local\Temp\tmp2dpph2mn\^#dt_mcu_lib#kernel#dt_common#inc#dt_common.h.gcov
               ['        -', '    0', 'Source', '../dt_mcu_lib/kernel/dt_common/inc/dt_common.h\n']
  source_fname C:\code\cc13xx_firmware\build_host\test\test_sim\CMakeFiles\test_sim_sds_testvector_map.dir\__\__\dt_mcu_lib\drivers_cc13xx\sds\sds_streaming_receiver\src\bitvec.c.gcda
  root         C:\code\cc13xx_firmware\build_host
  fname        c:\code\cc13xx_firmware\build_host\..\dt_mcu_lib\kernel\dt_common\inc\dt_common.h
```

**Comment by latk** [comment]
The problem is that the casing of the Windows drive letter is inconsistent. Gcovr is case-sensitive. Your Python produces paths that start with `c:` whereas you provided a root directory starting with `C:`. This was also discussed in #230.

You can avoid this problem by using a lower-case drive letter. But I'm not sure what the general fix would be.

**Comment by tuze-kuyucu** [comment]
yes that seems to be my issue, thanks a lot!
