### ISSUE TITLE
(WARNING) Unrecognized GCOV output

### ISSUE THREAD

**Issue by andyLiuChina** [gcovr/gcovr#396]
HI, please help to this problem.

The C compiler identification is GNU 6.3.0

CMD: ['gcovr', '--filter=.*\\.c$', '--exclude=.*Mock.*', '--root=C:\\Users\\cnaliu\\Desktop\\myGitWorkspace\\SourceC0\\cApp', '--object-directory=C:\\Users\\cnaliu\\Desktop\\myGitWorkspace\\SourceC0\\cApp\\Output\\UnitTest', '--sort-percentage', '--keep', '--html', '--output=C:\\Users\\cnaliu\\Desktop\\myGitWorkspace\\SourceC0\\cApp\\Output\\UnitTest\\Report\\Coverage.html']

(WARNING) Unrecognized GCOV output for C:\Users\cnaliu\Desktop\myGitWorkspace\SourceC0\cApp\BSW\SvHIDC\lib\src\IPMMessageHandle\IPMMessageHandle.c

ptSendData->wDataLen = (unsigned short)(SVHIDC_IPM_HEADER_SIZE_IN_BYTES + wDataLen);

This is indicative of a gcov output parse error.

Please report this to the gcovr developers

at <https://github.com/gcovr/gcovr/issues>.

(ERROR) Exiting because of parse errors.

You can run gcovr with --gcov-ignore-parse-errors

to continue anyway.

Traceback (most recent call last):

File "c:\users\cnaliu\appdata\local\programs\python\python38\lib\site-packages\gcovr\workers.py", line 71, in worker

work(*args, **kwargs)

File "c:\users\cnaliu\appdata\local\programs\python\python38\lib\site-packages\gcovr\gcov.py", line 589, in process_datafile

done = run_gcov_and_process_files(

File "c:\users\cnaliu\appdata\local\programs\python\python38\lib\site-packages\gcovr\gcov.py", line 676, in run_gcov_and_process_files

process_gcov_data(fname, covdata, abs_filename, options)

File "c:\users\cnaliu\appdata\local\programs\python\python38\lib\site-packages\gcovr\gcov.py", line 119, in process_gcov_data

parser.parse_all_lines(

File "c:\users\cnaliu\appdata\local\programs\python\python38\lib\site-packages\gcovr\gcov.py", line 240, in parse_all_lines

self.check_unrecognized_lines(ignore_parse_errors=ignore_parse_errors)

File "c:\users\cnaliu\appdata\local\programs\python\python38\lib\site-packages\gcovr\gcov.py", line 511, in check_unrecognized_lines

sys.exit(1)

SystemExit: 1

**Comment by andyLiuChina** [comment]
contain windows specific chatater '^m'.
