### ISSUE TITLE
gcovr fails to find gcov on Windows

### ISSUE THREAD

**Issue by ilayavimal10** [gcovr/gcovr#497]
> I am facing following issues while running gcovr -r . command

> Could you please help to resolve this issues ?

```
Traceback (most recent call last):
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 76, in worker
    work(*args, **kwargs)
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 620, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 684, in run_gcov_and_process_files
    out, err = subprocess.Popen(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 76, in worker
    work(*args, **kwargs)
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 620, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 684, in run_gcov_and_process_files
    out, err = subprocess.Popen(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\ILA1COB\AppData\Local\Programs\python\Python39\Scripts\gcovr-script.py", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.0', 'console_scripts', 'gcovr')())
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\__main__.py", line 275, in main
    collect_coverage_from_gcov(covdata, options, logger)
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\__main__.py", line 337, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 165, in __exit__
    self.wait()
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 156, in wait
    raise self.exceptions[0][1]
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\__main__.py", line 337, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 156, in wait
```

**Comment by latk** [comment]
The error indicates that `gcov` is not available. Gcov should have been installed alongside GCC. If your gcov executable has a different name or is placed in an unusual path, you can tell gcovr about this via the [--gcov-executable](https://gcovr.com/en/5.0/guide.html#cmdoption-gcovr-gcov-executable) option. To get more information about what is going wrong here, you could also run gcovr in --verbose mode.

**Comment by ilayavimal10** [comment]
Gcov.exe is file available in inside mingw compiler path. Without example.gcno , example.gcda files i am able to execute gcovr -r . command successfully , when I run the same command with that two files (example.gcno , example.gcda) I am getting above issues .

**Comment by inorton** [comment]
@ilayavimal10 gcovr will by default just run `gcov` so it needs to be on `PATH`. If it isn't then you need to supply the full path to a `gcov` program using the `--gcov-executable` option

**Comment by ilayavimal10** [comment]
\python\Python39\Scripts>C:\xxxxx\mingw\comp_5.3.0_w64_2f\bin\gcov.exe gcovr -r .
gcovr.gcno:cannot open notes file
.gcno:cannot open notes file
No executable lines

Getting this error..

**Comment by latk** [comment]
> `\python\Python39\Scripts>C:\xxxxx\mingw\comp_5.3.0_w64_2f\bin\gcov.exe gcovr -r .`

That command would try to use gcov to process coverage for the gcovr program, if it were native code. That is not the case, it cannot work, and it does not work as explained by the “gcovr.gcno: cannot open notes file” message.

You probably want this instead:

```cmd
> gcovr --gcov-executable C:\xxxxx\mingw\comp_5.3.0_w64_2f\bin\gcov.exe
```

This runs gcovr, but tells it where to find your gcov.

**Comment by ilayavimal10** [comment]
C:\xxx\xxxx\Desktop\GCOV_Test\GCOV\xxxxx>C:\xxxx\xxxxx\AppData\Local\Programs\python\Python39\Scripts\gcovr C:\toolbase\mingw\comp_5.3.0_w64_2f\bin\gcov.exe
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
------------------------------------------------------------------------------
TOTAL                                          0       0    --%
------------------------------------------------------------------------------


I am getting only empty report i am not getting exact coverage report . I am running this command in .gcov,.gcda,gcno file location only but still i am getting only empty coverage i am not getting proper coverage . Could please help on this issues.

**Comment by ilayavimal10** [comment]
C:\Users\xxxx\Desktop\GCOV_Test\GCOV\Ref_Source_new>C:\Users\xxxxx\AppData\Local\Programs\python\Python39\Scripts\gcovr C:\toolbase\mingw\comp_5.3.0_w64_2f\bin\gcov.exe
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
------------------------------------------------------------------------------
TOTAL                                          0       0    --%
------------------------------------------------------------------------------

**Comment by latk** [comment]
Those commands are all missing the `--gcov-executable` flag. It is not sufficient to just list the gcov path.

If you're getting an empty report this either means that no gcda/gcno files were found, or that all coverage information was filtered out because it was outside of the project root. The argument `-r .` says that the root of your project is the current directory, and that coverage for source files outside of that directory should be ignored. See [*Using Filters* in the gcovr 5.0 manual](https://gcovr.com/en/5.0/guide.html#using-filters) for further details on the filtering system.

To see what is being found and what is being filtered out, consider running gcovr in `--verbose` mode.

**Comment by ilayavimal10** [comment]
**C:\Users\xxxxx\Desktop\GCOV_Test\GCOV\Ref_Source_new>C:\Users\xxxxx\AppData\Local\Programs\python\Python39\Scripts\gcovr --gcov-executable C:\toolbase\mingw\comp_5.3.0_w64_2f\bin\gcov.exe**
Traceback (most recent call last):
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 76, in worker
    work(*args, **kwargs)
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 620, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 684, in run_gcov_and_process_files
    out, err = subprocess.Popen(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 76, in worker
    work(*args, **kwargs)
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 620, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 684, in run_gcov_and_process_files
    out, err = subprocess.Popen(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\ILA1COB\AppData\Local\Programs\python\Python39\Scripts\gcovr-script.py", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.0', 'console_scripts', 'gcovr')())
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\__main__.py", line 275, in main
    collect_coverage_from_gcov(covdata, options, logger)
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\__main__.py", line 337, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 165, in __exit__
    self.wait()
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 156, in wait
    raise self.exceptions[0][1]
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\__main__.py", line 337, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 156, in wait
    raise self.exceptions[0][1]
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\workers.py", line 76, in worker
    work(*args, **kwargs)
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 620, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\site-packages\gcovr\gcov.py", line 684, in run_gcov_and_process_files
    out, err = subprocess.Popen(
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\ila1cob\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Now i am getting this error , But i have already generated .gcov , .gcda , .gcno but still i am getting above error

**Comment by latk** [comment]
We are now back at the same error from the original question, which indicates that the gcov program somehow doesn't work.

Does running the following command show a help message?

    C:\toolbase\mingw\comp_5.3.0_w64_2f\bin\gcov.exe --help

You can also run gcovr in --verbose mode to see how gcov is actually being invoked.

**Comment by ilayavimal10** [comment]
It's working fine with below command 
**C:\Users\xxxxxx\AppData\Local\Programs\python\Python39\Scripts\gcovr --gcov-executable gcov -r . --html -o example-html.html**

We can close the ticket and Thank you so much for the quick response and support  :)
