### ISSUE TITLE
`KeyError: 'Source'` after update to 5.1

### ISSUE THREAD

**Issue by sergiud** [gcovr/gcovr#588]
**Describe the bug**
This is another issue I encountered after updating from 5.0 to 5.1. In contrast to my previous report #587, this is on a different system and in a different project.
```console
$ cd build/
$  gcovr -r ${WORKSPACE} --exclude-function-lines --exclude-throw-branches --exclude-unreachable-branches -s --sonarqube ${PROJECT_DIR}/report.xml --html -o ${PROJECT_DIR}/coverage/report.html
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 170, in __exit__
    self.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
```

**To Reproduce**
Similar to my previous report #587, the problem occurs in a (different) large project that previously used gcovr 5.0. Unfortunately, I don't even know where I can start looking.

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - GCC version 9.4
 - GCOVR version 5.1
 - Project directory layout:
   - `include/`
   - `src/`
   - `build/`

**Comment by Spacetown** [comment]
Can you also run with `--verbose` here? It seems that gcov creates a coverage file but there is no Source present in the file.

**Comment by latk** [comment]
Again, sorry for these problems, but thank you for this bug report.

Every .gcov file that's generated by the GCC gcov tool should start with a line like:

```none
        -:    0:Source:tmp.cpp
```

Gcovr needs this information to figure out which source file this coverage information references. Your error indicates that this line is absent or malformed.

Again, could you perhaps running with the `gcovr --verbose` option so that we can see which .gcov file this error originates in? Then, running with the `gcovr --keep` option should avoid deleting the intermediate gcov file so that we can inspect the first few lines.

**Comment by sergiud** [comment]
Thank you for looking into this. For completeness I've attached the log from #587.
[gcovr-keyerror-source.log](https://github.com/gcovr/gcovr/files/8365827/gcovr-keyerror-source.log)
Note that this log is not for the project and system reported above but on a system running ArchLinux with a recent GCC (see my other issue #587). I can try producing a verbose log on Ubuntu as well if needed.

**Comment by Spacetown** [comment]
Thers is 22 times the message `branch x taken -y` times from #583. Can you run following command and post the head of the file with the keys?
```
(DEBUG) Running gcov: 'gcov /home/sergiu/Projects/tracker/build-debug/CMakeFiles/vision_core.dir/src/vision/piecewiseaffinetransform.cpp.gcno --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /home/sergiu/Projects/tracker/build-debug/CMakeFiles/vision_core.dir/src/vision' in '/home/sergiu/Projects/tracker'
```

**Comment by sergiud** [comment]
Interesting. I get:
```
/home/sergiu/Projects/tracker/build-debug/CMakeFiles/vision_core.dir/src/vision/piecewiseaffinetransform.cpp.gcno:version '408*', prefer 'B12*'
```
followed by `Segmentation fault (core dumped)`.

**Comment by Spacetown** [comment]
This segmentation fault points to corrupt gcno file.
Can you check your project with clang? In #583 there wasn't a problem with clang.

The filters work on source file level and not on the level of the gcda files.

**Comment by latk** [comment]
> version '408*', prefer 'B12*'

Are you using matching gcc and gcov versions? If you've configured your compilation process e.g. to use `gcc-11` or `/path/to/custom/gcc`, then you must use a corresponding `gcov-11` or `/path/to/custom/gcov`, respectively. If you've switched compilers between runs, you must make a clean build.

Background: when compiling with `--coverage`, GCC outputs information about the compilation unit in .gcno files. Later, the gcov tool reads this info and combines it with the coverage counters written in .gcda. Thus, a matching gcov is required to parse GCC's data format.

**Comment by sergiud** [comment]
My current setup is this:
```
include/
src/
build-debug/ # Clang build (should not be considered)
build-coverage/ # GCC 11.2 build
```
As such, the `.gcno` files from the unused `build-debug/` were generated by clang, yes. However, I'm not sure why these are picked up by gcovr running in `build-coverage/` with filters set to `include/` and `src/`. Am I missing something here?

After moving the unused `build-debug` directory out of the project root, I get the attached log.

[gcovr.log](https://github.com/gcovr/gcovr/files/8366046/gcovr.log)

**Comment by sergiud** [comment]
I also see that with `-k` `.gcov` files are created directly in the project root even though I'm running gcovr from the `build-coverage/` subdirectory. Is this possibly the issue?

**Comment by Spacetown** [comment]
You use the option `-r ${WORKSPACE}` which scans `${WORKSPACE}` instead of the current working directory. Can you remove this option?

**Comment by sergiud** [comment]
If I do that gcovr completes but the coverage is 0 for every metric.

**Comment by latk** [comment]
(or instead of removing -r, explicitly tell gcovr to only search the current directory by adding a `.` argument)

**Comment by sergiud** [comment]
That lets gcovr completes as well but the coverage is still 0 (which is not the case.)

**Comment by latk** [comment]
> files are created directly in the project root even though I'm running gcovr from the build-coverage/ subdirectory.

It is possibly *related* to the issue, but not itself a problem. Gcovr tries invoking `gcov` from different directories until something works. The project root directory is one of those attempts. Ideally, gcov is invoked from the same directory from which the compiler was invoked, but this should not matter in case `-fprofile-abs-path` was used during compilation.

> That lets gcovr complete as well but the coverage is still 0 (which is not the case.).

Your `--root` in that invocation was the `tracker/build-coverage` directory, not the `tracker` project root. Since no source files are within that root, all coverage was excluded.

Something like `cd build-coverage; gcovr --root .. OTHER_OPTIONS .` (note the `.`) should work correctly in the sense of avoiding the build-debug files (which were picked up in a previous run!). Alternatively, `gcovr OTHER_OPTIONS build-coverage` might work (almost but not quite equivalent).

**Comment by latk** [comment]
> still produces KeyError. A bunch of .gcov files are again generated in the project root.

The next time this happens, could you perhaps provide the `head *.gcov` output to see the beginning of these files? I'm only interested in the header lines beginning with ` -:  0:` so feel free to adjust the cutoff to omit any actual code.

The gcovr-5.0 log also seems to be corrupted: it contains fragments of a .gcov file, for example line 87053 to 87078. This might be an unrelated bug, but in any case it would be helpful for debugging to deactivate the gcov-parallel option (it rarely speeds things up anyway).

**Comment by sergiud** [comment]
Using `--gcov-ignore-parse-errors` as suggested by gcovr output finally lets the analysis finish. Setting again `gcov-parallel` to `yes` triggers the `KeyError` though.

**Comment by latk** [comment]
> Setting again `gcov-parallel` to `yes` triggers the `KeyError` though.

To clarify, are you seeing a correlation between `gcov-parallel`/`-j` and the KeyError?

**Comment by sergiud** [comment]
Yes, once parallel processing is enabled either `KeyError` or `FileNotFoundError` (#587) occur randomly.

**Comment by latk** [comment]
Hmm, then I think the next release should (temporarily?) disable parallel processing until that part of the code base can be overhauled.

I think there's a good chance the parallel-processing code has subtle bugs, also taking into account some background on #572.

This should not negatively impact most users since performance benefits of gcov-parallel are marginal for most project layouts (only one gcov process per working directory can run at the same time).

But parallel processing would be safe to re-enable at the latest when JSON input is implemented, someday (cf #282).

**Comment by sergiud** [comment]
FYI, I've attached a log where `KeyError` and `FileNotFoundError` (#587) occur at the same time. These issues seem to be related.
[gcovr.log](https://github.com/gcovr/gcovr/files/8374273/gcovr.log)

**Comment by Spacetown** [comment]
@latk Is it possible that the directory lock doesn't work? In 5.0 the files where created in a temporary folder which was changed by #525 because the source files where not found.

**Comment by Spacetown** [comment]
I think I've found the problem. Following block should be done one level deeper inside the directory lock:
https://github.com/gcovr/gcovr/blob/8106d593db490082135eed9167536f621e1b64b5/gcovr/gcov.py#L484-L495

If I provide you a priavte branch can you use it in the CI to verify this?

**Comment by sergiud** [comment]
Sure, I'll verify it using my project referenced in the logs.

**Comment by Spacetown** [comment]
I'm waiting for your response.
@latk Shall I wait for your changes if this works or will you rebase?

**Comment by latk** [comment]
@Spacetown go ahead, I'm only tinkering with other parts.

**Comment by sergiud** [comment]
@Spacetown I ran gcovr from 0f11c3b2965ed5444cf640a17ecf4e83f0c1bb21 several times and it worked every time without problems. Thank you!
[gcovr.log](https://github.com/gcovr/gcovr/files/8374456/gcovr.log)

**Comment by jaapcrezee** [comment]
Is this really fixed?
I just installed the latest gcovr (as of writing) using: `pip install git+https://github.com/gcovr/gcovr.git` and this still gives me:
```
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 304, in main
    covdata = collect_coverage_from_gcov(options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 363, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 171, in __exit__
    self.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.8/dist-packages/gcovr/__main__.py", line 363, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 110, in process_gcov_data
    metadata = parse_metadata(lines)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 256, in parse_metadata
    raise RuntimeError(
RuntimeError: Missing key 'Source' in metadata. GCOV data was >><< End of GCOV data
```

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
```

**Comment by Spacetown** [comment]
@jaapcrezee Please can you open a new issue and provide more information (--verbose)?
