### ISSUE TITLE
gcovr: Unrecognized GCOV output for ../systemd/src/shared/exec-util.c

### ISSUE THREAD

**Issue by mklntf** [gcovr/gcovr#610]
**Describe the bug**
I wanted to build the coverage for systemd (commit: 4d54310da5ac864cf407823cc07df743548527cc)
via the command `meson setup -Db_coverage=true build && meson test -C build && ninja coverage-html -C build`.
It failed with the following error message:

```
[1/1] Generates HTML coverage report
FAILED: meson-coverage-html
/usr/bin/meson --internal coverage --html /home/markus/dev/repos/systemd /home/markus/dev/repos/systemd/subprojects /home/markus/dev/repos/systemd/build /home/markus/dev/repos/systemd/build/meson-logs
(WARNING) Unrecognized GCOV output for /home/markus/dev/repos/systemd/src/shared/exec-util.c
	  branch  2 taken -6
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
	UnknownLineType: branch  2 taken -6
(ERROR) Exiting because of parse errors.
	You can run gcovr with --gcov-ignore-parse-errors
	to continue anyway.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 145, in process_gcov_data
    coverage = parse_coverage(
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 370, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 509, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 322, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 777, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: branch  2 taken -6
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 145, in process_gcov_data
    coverage = parse_coverage(
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 370, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 509, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 322, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 777, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: branch  2 taken -6
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.1', 'console_scripts', 'gcovr')())
  File "/usr/lib/python3.10/site-packages/gcovr/__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "/usr/lib/python3.10/site-packages/gcovr/__main__.py", line 360, in collect_coverage_from_gcov
    with Workers(
  File "/usr/lib/python3.10/site-packages/gcovr/workers.py", line 170, in __exit__
    self.wait()
  File "/usr/lib/python3.10/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3.10/site-packages/gcovr/__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/lib/python3.10/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov.py", line 145, in process_gcov_data
    coverage = parse_coverage(
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 370, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 509, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 322, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
  File "/usr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 777, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: branch  2 taken -6
Traceback (most recent call last):
  File "/usr/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.62.0', 'console_scripts', 'meson')())
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 269, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 258, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 201, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/coverage.py", line 182, in run
    return coverage(options.outputs, options.source_root,
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/coverage.py", line 139, in coverage
    subprocess.check_call(gcovr_base_cmd +
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcovr', '-r', '/home/markus/dev/repos/systemd', '/home/markus/dev/repos/systemd/build', '--html', '--html-details', '--print-summary', '-e', '/home/markus/dev/repos/systemd/subprojects', '-o', '/home/markus/dev/repos/systemd/build/meson-logs/coveragereport/index.html']' returned non-zero exit status 1.
ninja: build stopped: subcommand failed.
```

I really have no idea what "UnknownLineType: branch  2 taken -6" is pointing to. Since the output asks to report it to the gcovr developers I opened this bug.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - GCC version 11.2.0
 - GCOVR version 5.1

**Comment by Spacetown** [comment]
This is related to #583 and is a problem of GCC. You can ignore this error as described in https://github.com/gcovr/gcovr/issues/583#issuecomment-1080352048.
