### ISSUE TITLE
macOS - gcovr awfully slow + creates .gcov files everywhre

### ISSUE THREAD

**Issue by ladislas** [gcovr/gcovr#618]
**Describe the bug**

When running on macOS Monterey, on Apple M1 Mac, gcovr now takes an awful lot of time, between 20/30 seconds when it was a few seconds before.

It now also randomly fails with the following error:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 93, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/san.cpp##faba66a619735a09c6f2f86bb3b4fa6f.gcov'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 93, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/san.cpp##faba66a619735a09c6f2f86bb3b4fa6f.gcov'
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/opt/homebrew/bin/gcovr", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.1', 'console_scripts', 'gcovr')())
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 360, in collect_coverage_from_gcov
    with Workers(
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 170, in __exit__
    self.wait()
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/opt/homebrew/Cellar/gcovr/5.1/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 93, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/san.cpp##faba66a619735a09c6f2f86bb3b4fa6f.gcov'
make[1]: *** [coverage] Error 1
make: *** [utc] Error 2
```

While running it creates tens of `something.h##1234568900.gcov` files such as `reverse_iterator.h##f0e04e9127fd9d3e36e110a99633d340.gcov` in location such as the project root, home directory, etc.

**To Reproduce**

Run gcovr under macOS Monterey

**Expected behavior**

To work again like it used to.

**Screenshots**

Result of `git status`

<img width="221" alt="image" src="https://user-images.githubusercontent.com/2206544/167315769-1c798994-1734-4f87-a0c3-8edc28a91fff.png">

`Home directory`

<img width="270" alt="image" src="https://user-images.githubusercontent.com/2206544/167315745-16d3debf-901a-4664-83cd-ff191dcc3666.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - GCC version 10.2
 - GCOVR version 5.1
 - Project directory layout: https://github.com/leka/LekaOS

**Additional context**

n/a

**Comment by ladislas** [comment]
The issue is not present on 5.0. Downgrading is the current workaround.

**Comment by Spacetown** [comment]
This should be fixed with #592. You can install the current master until the next release.
The 5.0 was faster but not correct because the result from the first run in  temp was used.
If no exception occurred the files are removed at the end.

**Comment by ladislas** [comment]
Thanks! Is there a way to put all those files "somewhere else" so that in case of an exception, I don't have scan all my computer to remove them? Some tmp directory in the project for example that we could gitignore

**Comment by Spacetown** [comment]
I think you can add `*.gcda`,  `*.gcno` and `*.gcov` to your `.gitignore`. We do this for our test:
https://github.com/gcovr/gcovr/blob/ba4de0ea3b4c69aec2b745b7174411d6867828e8/gcovr/tests/.gitignore#L24-L26
