### ISSUE TITLE
Traceback when called without "-r" / "--root" parameter

### ISSUE THREAD

**Issue by silwol** [gcovr/gcovr#62]
Calling gcovr 3.2 without the root parameter gives this traceback:

```
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 1972, in <module>
    print_text_report(covdata)
  File "/usr/bin/gcovr", line 822, in print_text_report
     OUTPUT.write("Directory: "+options.root+"\n")
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

gcovr 3.1 gave an empty but more friendly output:

```
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
------------------------------------------------------------------------------
TOTAL                                          0       0    --%
------------------------------------------------------------------------------
```

I would prefer to either return to the behavior of 3.1, or to print a message stating what the problem is. Maybe setting options.root to a default value before using it the first time would be enough already.

**Comment by latk** [comment]
Thank you for your reports! This was fixed in commit e7d1bbe62181b003cf69517fb87994717a274184, and is part of the 3.4 release.

The problems with `--root` should also be fixed in the meanwhile, and the path is escaped properly.
