### ISSUE TITLE
gcovr 5.1 crashes when collecting coverage from tests compiled with gcc 12

### ISSUE THREAD

**Issue by b1ackviking** [gcovr/gcovr#620]
**Describe the bug**

Gcovr crashes from time to time when collecting coverage from unit tests compiled with GCC 12.

**To Reproduce**

1. Build unit tests with GCC 12.
2. Execute tests.
3. Run gcvor in the project directory (see below).

**Expected behavior**

Gcovr reports coverage without any errors.

**Desktop:**

 - OS: Arch Linux (kernel 5.17)
 - GCC version 12.1
 - GCOVR version 5.1 installed using pipenv
 - Project directory layout: same as https://github.com/b1ackviking/cpp-project-template
 - gcovr.cfg

```
filter = lib
cobertura = coverage.xml
cobertura-pretty = yes
print-summary = yes
gcov-parallel = yes
delete-gcov-files = yes
```

**Logs**

In a project derived from [this template](https://github.com/b1ackviking/cpp-project-template), I install google test with Conan and build the tests with CMake as follows:

```
(bms48v) ➜  bms48v git:(sy68940) export BUILD_TYPE=Debug
(bms48v) ➜  bms48v git:(sy68940) export TOOLCHAIN=cmake/gcc.cmake
(bms48v) ➜  bms48v git:(sy68940) export PROFILE=conan/gcc-12 
(bms48v) ➜  bms48v git:(sy68940) conan install -if build -b missing . -pr:b default \
  -pr:h default -pr:h $PROFILE \
  -s build_type=$BUILD_TYPE -o board=host \
  -c:h tools.cmake.cmaketoolchain:user_toolchain=\[\"$(pwd)/$TOOLCHAIN\"\] \
  -e:h CMAKE_TOOLCHAIN_FILE=$(pwd)/$TOOLCHAIN
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
os_build=Linux
[options]
board=host
[build_requires]
[env]
CMAKE_TOOLCHAIN_FILE=/home/b1ack/projects/bms48v/cmake/gcc.cmake
[conf]
tools.cmake.cmaketoolchain:user_toolchain=['/home/b1ack/projects/bms48v/cmake/gcc.cmake']

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py: Installing package
Requirements
    gtest/1.11.0 from 'conancenter' - Cache
Packages
    gtest/1.11.0:e9736fd483ecabd23c9a588c3c3d5359d113bfd5 - Cache

Installing (downloading, building) binaries...
gtest/1.11.0: Already installed!
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Calling generate()
conanfile.py: Aggregating env generators
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
(bms48v) ➜  bms48v git:(sy68940) cmake -B build -S . --toolchain build/conan_toolchain.cmake \
  -D CMAKE_BUILD_TYPE=$BUILD_TYPE \
  -D ENABLE_COVERAGE=TRUE \
  -D ENABLE_SANITIZER_ADDRESS=TRUE \
  -D ENABLE_SANITIZER_LEAK=TRUE \
  -D ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=TRUE
-- Using Conan toolchain: /home/b1ack/projects/bms48v/build/conan_toolchain.cmake
-- The CXX compiler identification is GNU 12.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- The C compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'gtest::gtest'
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'gtest::gtest'
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'gtest::gtest'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/b1ack/projects/bms48v/build
(bms48v) ➜  bms48v git:(sy68940) cmake --build build --config $BUILD_TYPE --parallel
[1/6] Building CXX object test/estd/CMakeFiles/estd-test.dir/estd-test.cpp.o
[2/6] Building CXX object test/math/CMakeFiles/math-test.dir/math-test.cpp.o
[5/6] Building CXX object test/sy68940/CMakeFiles/sy68940-test.dir/sy68940-test.cpp.o
[6/6] Linking CXX executable test/sy68940/sy68940-test
```

Then I run ctest and gcvor to collect test coverage:

```
# first attempt

(bms48v) ➜  bms48v git:(sy68940) export GCOV=gcov
(bms48v) ➜  bms48v git:(sy68940) ctest --test-dir build -C $BUILD_TYPE --output-on-failure --progress --parallel 2 && gcovr --txt
Internal ctest changing into directory: /home/b1ack/projects/bms48v/build
Test project /home/b1ack/projects/bms48v/build
24/24 Test  #3: estd.assemble_bytes
100% tests passed, 0 tests failed out of 24

Total Test time (real) =   0.20 sec
Traceback (most recent call last):
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
Traceback (most recent call last):
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/__main__.py", line 360, in collect_coverage_from_gcov
    with Workers(
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 170, in __exit__
    self.wait()
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    metadata["Source"].strip(),
KeyError: 'Source'


# second attempt

(bms48v) ➜  bms48v git:(sy68940) ✗ ctest --test-dir build -C $BUILD_TYPE --output-on-failure --progress --parallel 2 && gcovr --txt
Internal ctest changing into directory: /home/b1ack/projects/bms48v/build
Test project /home/b1ack/projects/bms48v/build
24/24 Test  #1: Math.FibonacciWorks
100% tests passed, 0 tests failed out of 24

Total Test time (real) =   0.20 sec
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
lib/estd/include/estd/bit.hpp                 11      11   100%   
lib/math/include/math/math.hpp                24      24   100%   
lib/sy68940/include/hardware/sy68940.hpp     178     178   100%   
------------------------------------------------------------------------------
TOTAL                                        213     213   100%
------------------------------------------------------------------------------
lines: 100.0% (213 out of 213)
functions: 100.0% (80 out of 80)
branches: 57.6% (76 out of 132)


# third attempt

(bms48v) ➜  bms48v git:(sy68940) ctest --test-dir build -C $BUILD_TYPE --output-on-failure --progress --parallel 2 && gcovr --txt
Internal ctest changing into directory: /home/b1ack/projects/bms48v/build
Test project /home/b1ack/projects/bms48v/build
24/24 Test  #3: estd.assemble_bytes
100% tests passed, 0 tests failed out of 24

Total Test time (real) =   0.21 sec
Traceback (most recent call last):
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 93, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/b1ack/projects/bms48v/gtest-message.h##70684581139a8bfa2cada3641d00a614.gcov'
Traceback (most recent call last):
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 93, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/b1ack/projects/bms48v/gtest-message.h##70684581139a8bfa2cada3641d00a614.gcov'
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/__main__.py", line 360, in collect_coverage_from_gcov
    with Workers(
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 170, in __exit__
    self.wait()
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/b1ack/.local/share/virtualenvs/bms48v-Vtwj0bky/lib/python3.10/site-packages/gcovr/gcov.py", line 93, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/b1ack/projects/bms48v/gtest-message.h##70684581139a8bfa2cada3641d00a614.gcov'


# fourth attempt

(bms48v) ➜  bms48v git:(sy68940) ✗ ctest --test-dir build -C $BUILD_TYPE --output-on-failure --progress --parallel 2 && gcovr --txt
Internal ctest changing into directory: /home/b1ack/projects/bms48v/build
Test project /home/b1ack/projects/bms48v/build
24/24 Test  #3: estd.assemble_bytes
100% tests passed, 0 tests failed out of 24

Total Test time (real) =   0.20 sec
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
lib/estd/include/estd/bit.hpp                 11      11   100%   
lib/math/include/math/math.hpp                24      24   100%   
lib/sy68940/include/hardware/sy68940.hpp     178     178   100%   
------------------------------------------------------------------------------
TOTAL                                        213     213   100%
------------------------------------------------------------------------------
lines: 100.0% (213 out of 213)
functions: 100.0% (80 out of 80)
branches: 57.6% (76 out of 132)
```

**Comment by Spacetown** [comment]
This issue is related to #588 and already fixed on the master branch. What I'm wondering is, that it only occur from time to time.

**Comment by b1ackviking** [comment]
@Spacetown It looks like `gcov-parallel = yes` is causing the issue. Disabling it fixes the problem.

Also, my observation is that Gcovr crashes much more frequently on unit tests compiled with GCC12 than unit tests compiled with Clang13. And crashes with Clang produce only `KeyError: 'Source'` exceptions, while crashes with GCC produce both `KeyError: 'Source'` and `FileNotFoundError` exceptions.

Here are the exact versions I am using:

```
(bms48v) ➜  bms48v git:(sy68940) ✗ gcc --version
gcc (GCC) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(bms48v) ➜  bms48v git:(sy68940) ✗ gcov --version
gcov (GCC) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(bms48v) ➜  bms48v git:(sy68940) ✗ clang --version
clang version 13.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
(bms48v) ➜  bms48v git:(sy68940) ✗ llvm-cov --version
LLVM (http://llvm.org/):
  LLVM version 13.0.1
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
(bms48v) ➜  bms48v git:(sy68940) ✗ gcovr --version
gcovr 5.1

Copyright (c) 2013-2022 the gcovr authors
Copyright (c) 2013 Sandia Corporation.
This software is distributed under the BSD License.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
```

**Comment by Spacetown** [comment]
Sorry, this was a typo. #587 is `FileNotFoundError` and #588 is `KeyError: 'Source'`. Both errors are fixed on the master branch.
Parallel processing is not reproducible and a little difference in timing between the calls can change everything.

**Comment by b1ackviking** [comment]
OK, thanks! Looking forward to the next release.

**Comment by aminya** [comment]
Could you tag a new release? This bug is breaking for some people.

**Comment by Spacetown** [comment]
You can install direct from the master branch until a new release is tagged or you can use the previous version.
