### ISSUE TITLE
gcovr 5.1 with --decisions flag: Assertion Error: assert count_false >= 0

### ISSUE THREAD

**Issue by ferbetanzo** [gcovr/gcovr#637]
**Describe the bug**
Running the latest gcovr 5.1 on our [code base](https://github.com/CQCL/tket) with the `--decisions` flag enabled, errors out with:
```
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/home/runner/.local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/__main__.py", line 308, in main
    collect_coverage_from_gcov(covdata, options)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/workers.py", line 170, in __exit__
    self.wait()
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/__main__.py", line 367, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/workers.py", line 161, in wait
    raise self.exceptions[0][1]
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/workers.py", line [77](https://github.com/CQCL/tket/runs/7128565614?check_suite_focus=true#step:15:78), in worker
    work(*args, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov.py", line 317, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov.py", line 4[90](https://github.com/CQCL/tket/runs/7128565614?check_suite_focus=true#step:15:91), in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov.py", line 145, in process_gcov_data
    coverage = parse_coverage(
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 368, in parse_coverage
    decision_parser.parse_all_lines()
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/decision_analysis.py", line 160, in parse_all_lines
    ).decision = DecisionCoverageConditional(
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/coverage.py", line 122, in __init__
    assert count_false >= [0](https://github.com/CQCL/tket/runs/7128565614?check_suite_focus=true#step:15:1)
AssertionError
```

The debug information does not say much:
```
> gcovr --print-summary --html --html-details -r ./tket/src/ --exclude-lines-by-pattern '.*\bTKET_ASSERT\(.*\);' --object-directory ${PWD}/build/tket/ -o test-coverage/index.html --decisions -v > test-coverage/summary.txt
(WARNING) relative referencing in --object-directory.
	this could cause strange errors when gcovr attempts to
	identify the original gcc working directory.
(DEBUG) Filters for --root: (1)
(DEBUG)  - re.compile('^/home/runner/work/tket/tket/tket/src/')
(DEBUG) Filters for --filter: (1)
(DEBUG)  - DirectoryPrefixFilter(/home/runner/work/tket/tket/tket/src/)
(DEBUG) Filters for --exclude: (0)
(DEBUG) Filters for --gcov-filter: (1)
(DEBUG)  - AlwaysMatchFilter()
(DEBUG) Filters for --gcov-exclude: (0)
(DEBUG) Filters for --exclude-directories: (0)
(DEBUG) Scanning directory ./tket/src/ for gcda/gcno files...
(DEBUG) Found 0 files (and will process 0)
(DEBUG) Scanning directory /home/runner/work/tket/tket/build/tket/ for gcda/gcno files...
(DEBUG) Found 286 files (and will process 143)
(DEBUG) Pool started with 1 threads
(DEBUG) Processing file: /home/runner/work/tket/tket/build/tket/Transformations/CMakeFiles/tket-Transformations.dir/Combinator.cpp.gcda
(DEBUG) Running gcov: 'gcov --help' in '.'
(DEBUG) Running gcov: 'gcov --help-hidden' in '.'
(DEBUG) Running gcov: 'gcov /home/runner/work/tket/tket/build/tket/Transformations/CMakeFiles/tket-Transformations.dir/Combinator.cpp.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /home/runner/work/tket/tket/build/tket/Transformations/CMakeFiles/tket-Transformations.dir' in '/home/runner/work/tket/tket/build/tket/'
(DEBUG) Finding source file corresponding to a gcov data file
  currdir      /home/runner/work/tket/tket
  gcov_fname   /home/runner/work/tket/tket/build/tket/Combinator.cpp##b4167a[11](https://github.com/CQCL/tket/runs/7128565614?check_suite_focus=true#step:15:12)9c4fa7f96a7802426dd[20](https://github.com/CQCL/tket/runs/7128565614?check_suite_focus=true#step:15:21)42a.gcov
  source_fname /home/runner/work/tket/tket/build/tket/Transformations/CMakeFiles/tket-Transformations.dir/Combinator.cpp.gcda
  root         /home/runner/work/tket/tket/tket/src
  fname        /home/runner/work/tket/tket/tket/src/Transformations/Combinator.cpp
(DEBUG) Parsing coverage data for file /home/runner/work/tket/tket/tket/src/Transformations/Combinator.cpp
(DEBUG) Starting the decision analysis
(DEBUG) Uncheckable decision at line 44
Traceback (most recent call last):
...
```

If we run `gcovr` without the `--decisions` flag, there's no error. Also, each time the flag is indeed used, the error is reported on different source files, and not all of them report `Uncheckable decision at line ...` problems.

You can look at the following for further information:
- The GH Actions run where this is observed: https://github.com/CQCL/tket/runs/7128565614?check_suite_focus=true
- The file that was being processed when the error was reported (for the previous run): https://github.com/CQCL/tket/blob/develop/tket/src/Transformations/Combinator.cpp

When run locally, printing some more debug information from the `DecisionParser -> parse_all_lines()` in `decision_analysis.py` shows that here:
```
                        self.coverage.line(
                            self.last_decision_line
                        ).decision = DecisionCoverageConditional(
                            exec_count, self.last_decision_line_exec_count - exec_count
                        )

```
the value of `self.last_decision_line_exec_count` is indeed (in some occassions) less than `exec_count`. Is this expected?

**Expected behavior**
If `gcovr` is capable of generating a report for some code base, it should not error out when the `--decisions` flag is used.

**Comment by Spacetown** [comment]
Can you try the latest master branch? There the debug output should be more verbose especially when an exception occurs.

**Comment by Spacetown** [comment]
```
Stderr of gcov was >>/home/fbetanzo/repos/tket/build/tket/Circuit/CMakeFiles/tket-Circuit.dir/Boxes.cpp.gcno:version 'B03*', prefer 'A94*'
/home/fbetanzo/repos/tket/build/tket/Circuit/CMakeFiles/tket-Circuit.dir/Boxes.cpp.gcda:version 'B03*', prefer version 'A94*'
<< End of stderr
```
Does the version of gcov match the version of GCC?

**Comment by ferbetanzo** [comment]
I've run the `gcovr` from the master branch now specifying the correct `gcov` version with: `--gcov-executable gcov-10`. The `prefer version` error message is gone. The process is still failing, but now with a different stack trace:

```
Current processed gcov file was '/home/runner/work/tket/tket/build/tket/UnitID.hpp##c024bcd95ec659c4a37faffa16ddae49.gcov'.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "/home/runner/work/tket/tket/gcovr/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 158, in process_gcov_data
    coverage = parse_coverage(
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov_parser.py", line 394, in parse_coverage
    decision_parser.parse_all_lines()
  File "/home/runner/work/tket/tket/gcovr/gcovr/decision_analysis.py", line 134, in parse_all_lines
    self.parse_one_line(lineno, code)
  File "/home/runner/work/tket/tket/gcovr/gcovr/decision_analysis.py", line 162, in parse_one_line
    line_coverage.branches[0].count,
KeyError: 0
Traceback (most recent call last):
  File "/home/runner/work/tket/tket/gcovr/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 158, in process_gcov_data
    coverage = parse_coverage(
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov_parser.py", line 394, in parse_coverage
    decision_parser.parse_all_lines()
  File "/home/runner/work/tket/tket/gcovr/gcovr/decision_analysis.py", line 134, in parse_all_lines
    self.parse_one_line(lineno, code)
  File "/home/runner/work/tket/tket/gcovr/gcovr/decision_analysis.py", line 162, in parse_one_line
    line_coverage.branches[0].count,
KeyError: 0
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/home/runner/.local/bin/gcovr", line 11, in <module>
    load_entry_point('gcovr', 'console_scripts', 'gcovr')()
  File "/home/runner/work/tket/tket/gcovr/gcovr/__main__.py", line 304, in main
    covdata = collect_coverage_from_gcov(options)
  File "/home/runner/work/tket/tket/gcovr/gcovr/__main__.py", line 363, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/home/runner/work/tket/tket/gcovr/gcovr/workers.py", line 171, in __exit__
    self.wait()
  File "/home/runner/work/tket/tket/gcovr/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/home/runner/work/tket/tket/gcovr/gcovr/__main__.py", line 363, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/home/runner/work/tket/tket/gcovr/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/home/runner/work/tket/tket/gcovr/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov.py", line 158, in process_gcov_data
    coverage = parse_coverage(
  File "/home/runner/work/tket/tket/gcovr/gcovr/gcov_parser.py", line 394, in parse_coverage
    decision_parser.parse_all_lines()
  File "/home/runner/work/tket/tket/gcovr/gcovr/decision_analysis.py", line 134, in parse_all_lines
    self.parse_one_line(lineno, code)
  File "/home/runner/work/tket/tket/gcovr/gcovr/decision_analysis.py", line 162, in parse_one_line
    line_coverage.branches[0].count,
KeyError: 0
```

Please see this run for the whole debugging output: https://github.com/CQCL/tket/runs/7319393787?check_suite_focus=true

**Comment by Spacetown** [comment]
Can you reduce this to a small example? The output is really huge. Can you post post the gcov file for the problematic source?

**Comment by Spacetown** [comment]
@latk Should we add debug statements for the current line of the gcov file? Or is a second option to activate a verbose parser better for this?
