### ISSUE TITLE
Requesting version throws exception with invalid path in configuration file

### ISSUE THREAD

**Issue by ToppDev** [gcovr/gcovr#695]
**Describe the bug**

Requesting the `--version` while having a configuration file `gcovr.cfg` with an invalid `html` path throws an error, because gcovr tries to access the path while parsing the arguments.

**To Reproduce**
1. Create the configuration file `gcovr.cfg` with the content
    ```
    html = coverage/index.html
    ```
2. Run the command `gcovr --version`

**Expected behavior**
Print the version and copyright
```
gcovr 5.2
```

**Current behavior**
Exception, because path does not exist
```
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gcovr/configuration.py", line 493, in _get_value_from_config_entry
    value = converter(cfg_entry.value)
  File "/usr/lib/python3.10/site-packages/gcovr/configuration.py", line 540, in <lambda>
    return lambda value: OutputOrDefault(value, basedir)
  File "/usr/lib/python3.10/site-packages/gcovr/configuration.py", line 107, in __init__
    self._check_output_and_make_abspath(os.getcwd() if basedir is None else basedir)
  File "/usr/lib/python3.10/site-packages/gcovr/configuration.py", line 149, in _check_output_and_make_abspath
    raise ArgumentTypeError(
argparse.ArgumentTypeError: Could not create output file 'coverage/index.html': No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gcovr", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.2', 'console_scripts', 'gcovr')())
  File "/usr/lib/python3.10/site-packages/gcovr/__main__.py", line 170, in main
    cfg_options = parse_config_into_dict(
  File "/usr/lib/python3.10/site-packages/gcovr/configuration.py", line 447, in parse_config_into_dict
    value = _get_value_from_config_entry(cfg_entry, option)
  File "/usr/lib/python3.10/site-packages/gcovr/configuration.py", line 495, in _get_value_from_config_entry
    raise cfg_entry.error(str(err))
ValueError: gcovr.cfg: 8: html: Could not create output file 'coverage/index.html': No such file or directory
```

**Desktop (please complete the following information):**
 - OS: Arch Linux (6.0.10-arch2-1)
 - GCC version: 12.2.0
 - GCOVR version: 5.2
 - Project directory layout:
   - gcovr.cfg
   - No other files

**Comment by Spacetown** [comment]
Thanks for reporting this. The version flag is checked after parsing the config files.
