### ISSUE TITLE
gcov errors hidden when invoked by gcovr

### ISSUE THREAD

**Issue by connorjclark** [gcovr/gcovr#702]
On Ubuntu when building with clang, I should have been using `llvm-cov gcov` as the gcov executable, but I had overlooked this. I think I found an issue with how gcovr invokes gcov and then suppresses its output, which would have indicated to me much faster that there was a problem.

With verbose mode on, I was getting output like this:

```
(DEBUG) Processing file: /home/runner/work/ZeldaClassic/ZeldaClassic/build/CMakeFiles/algif.dir/Coverage/allegro-addons/algif/src/load_gif.cpp.gcda
(DEBUG) Running gcov: 'gcov /home/runner/work/ZeldaClassic/ZeldaClassic/build/CMakeFiles/algif.dir/Coverage/allegro-addons/algif/src/load_gif.cpp.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /home/runner/work/ZeldaClassic/ZeldaClassic/build/CMakeFiles/algif.dir/Coverage/allegro-addons/algif/src' in '/home/runner/work/ZeldaClassic/ZeldaClassic'
(DEBUG) Processing file: /home/runner/work/ZeldaClassic/ZeldaClassic/build/CMakeFiles/zelda.dir/Coverage/src/zc/zc_items.cpp.gcda
(DEBUG) Running gcov: 'gcov /home/runner/work/ZeldaClassic/ZeldaClassic/build/CMakeFiles/zelda.dir/Coverage/src/zc/zc_items.cpp.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /home/runner/work/ZeldaClassic/ZeldaClassic/build/CMakeFiles/zelda.dir/Coverage/src/zc' in '/home/runner/work/ZeldaClassic/ZeldaClassic'
```

And the end result was no coverage being collected. Whereas locally I got tons more info after each `gcov` telling me about the source file it located, and a full coverage report.

I eventually thought to run `gcov /home/runner/work/ZeldaClassic/ZeldaClassic/build/CMakeFiles/algif.dir/Coverage/allegro-addons/algif/src/load_gif.cpp.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /home/runner/work/ZeldaClassic/ZeldaClassic/build/CMakeFiles/algif.dir/Coverage/allegro-addons/algif/src` in my CI (github actions) and saw it gave me an error like:

```
... .gcno:version '402*', prefer '408*'
Segmentation fault (core dumped)
```

Which made me realize I had the wrong gcov. Turns out I didn't realize that since I was locally running on OSX, my `/usr/bin/gcov` was truly llvm's gcov, which is why the defaults worked locally but not on a remote Ubuntu machine.

Anyway, the TLDR-it looks like gcovr may be hiding the output of gcov if it errors? Would be great to print it instead.

**Comment by Spacetown** [comment]
Can you check this with the master branch? Since #653  we raise an exception if the return code of gcov isn't 0.

**Comment by connorjclark** [comment]
Full output w/ master:

```
(DEBUG) Filters for --root: (1)
(DEBUG)  - re.compile('^/home/runner/work/ZeldaClassic/ZeldaClassic/')
(DEBUG) Filters for --filter: (1)
(DEBUG)  - RelativeFilter(src root=/home/runner/work/ZeldaClassic/ZeldaClassic)
(DEBUG) Filters for --exclude: (7)
(DEBUG)  - RelativeFilter(src/dialog root=/home/runner/work/ZeldaClassic/ZeldaClassic)
(DEBUG)  - RelativeFilter(src/gui root=/home/runner/work/ZeldaClassic/ZeldaClassic)
(DEBUG)  - RelativeFilter(src/editbox root=/home/runner/work/ZeldaClassic/ZeldaClassic)
(DEBUG)  - RelativeFilter(src/jwin root=/home/runner/work/ZeldaClassic/ZeldaClassic)
(DEBUG)  - RelativeFilter(src/base/jwinfsel root=/home/runner/work/ZeldaClassic/ZeldaClassic)
(DEBUG)  - RelativeFilter(src/base/gui root=/home/runner/work/ZeldaClassic/ZeldaClassic)
(DEBUG)  - RelativeFilter(src/base/process_management root=/home/runner/work/ZeldaClassic/ZeldaClassic)
(DEBUG) Filters for --gcov-filter: (1)
(DEBUG)  - AlwaysMatchFilter()
(DEBUG) Filters for --gcov-exclude: (0)
(DEBUG) Filters for --exclude-directories: (0)
(DEBUG) Scanning directory . for gcda/gcno files...
(DEBUG) Found 300 files (and will process 154)
(DEBUG) Pool started with 1 threads
(DEBUG) Processing file: /home/runner/work/ZeldaClassic/ZeldaClassic/build/_deps/gme_external-build/gme/CMakeFiles/gme.dir/Coverage/M3u_Playlist.cpp.gcda
(DEBUG) Running gcov: 'gcov --help' in '.'
(DEBUG) Running gcov: 'gcov --help-hidden' in '.'
(DEBUG) Running gcov: 'gcov /home/runner/work/ZeldaClassic/ZeldaClassic/build/_deps/gme_external-build/gme/CMakeFiles/gme.dir/Coverage/M3u_Playlist.cpp.gcda --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /home/runner/work/ZeldaClassic/ZeldaClassic/build/_deps/gme_external-build/gme/CMakeFiles/gme.dir/Coverage' in '/home/runner/work/ZeldaClassic/ZeldaClassic'
(ERROR) Trouble processing '/home/runner/work/ZeldaClassic/ZeldaClassic/build/_deps/gme_external-build/gme/CMakeFiles/gme.dir/Coverage/M3u_Playlist.cpp.gcda' with working directory '/home/runner/work/ZeldaClassic/ZeldaClassic'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 328, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 534, in run_gcov_and_process_files
    out, err = gcov_cmd.run_with_args(
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 5[13](https://github.com/connorjclark/ZeldaClassic/actions/runs/3721921399/jobs/6312408123#step:9:14), in run_with_args
    raise RuntimeError(
RuntimeError: GCOV returncode was -11 (exited by signal).
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 328, in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 534, in run_gcov_and_process_files
    out, err = gcov_cmd.run_with_args(
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 513, in run_with_args
    raise RuntimeError(
RuntimeError: GCOV returncode was -11 (exited by signal).
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/gcovr/__main__.py", line 327, in main
    covdata = collect_coverage_from_gcov(options)
  File "/usr/local/lib/python3.10/dist-packages/gcovr/__main__.py", line 379, in collect_coverage_from_gcov
    with Workers(
  File "/usr/local/lib/python3.10/dist-packages/gcovr/workers.py", line 171, in __exit__
    self.wait()
  File "/usr/local/lib/python3.10/dist-packages/gcovr/workers.py", line [16](https://github.com/connorjclark/ZeldaClassic/actions/runs/3721921399/jobs/6312408123#step:9:17)2, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.10/dist-packages/gcovr/__main__.py", line 386, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.10/dist-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.10/dist-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 3[28](https://github.com/connorjclark/ZeldaClassic/actions/runs/3721921399/jobs/6312408123#step:9:29), in process_datafile
    done = run_gcov_and_process_files(
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 5[34](https://github.com/connorjclark/ZeldaClassic/actions/runs/3721921399/jobs/6312408123#step:9:35), in run_gcov_and_process_files
    out, err = gcov_cmd.run_with_args(
  File "/usr/local/lib/python3.10/dist-packages/gcovr/gcov.py", line 513, in run_with_args
    raise RuntimeError(
RuntimeError: GCOV returncode was -11 (exited by signal).
```

Exception thrown as expected since gcov segfaults, but still no error message (which would highlight that the problem was a version mismatch)

**Comment by Spacetown** [comment]
There was a signal from gcov without any output (`None`). -11 is the SIGSEGV.

**Comment by connorjclark** [comment]
No idea why it's None when running it explicitly prints a segfault message + the thing about the version mismatch. Regardless, the exception is a loud enough signal to point someone toward investigating the `gcov` executable, so feel free to close this.

**Comment by Spacetown** [comment]
Is it possible, that the message is printed from the shell itself? I don't know how the pipes brave when a exception occur.
