### ISSUE TITLE
Unrecognized GCOV output: function returned NAN

### ISSUE THREAD

**Issue by nazariig** [gcovr/gcovr#708]
**Describe the bug**
GCOVR errros are seen during files parsing.

Error log:
```
+ gcovr --version
gcovr 5.2

Copyright (c) 2013-2022 the gcovr authors
Copyright (c) 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
+ find SAI/meta -name '*.gc*'
+ xargs rm -vf
removed 'SAI/meta/libsaimetadata_la-saimetadata.gcno'
removed 'SAI/meta/libsaimetadata_la-saimetadatautils.gcno'
removed 'SAI/meta/.libs/libsaimetadata_la-saimetadata.gcno'
removed 'SAI/meta/.libs/libsaimetadata_la-saimetadatautils.gcno'
removed 'SAI/meta/.libs/libsaimetadata_la-saimetadatautils.gcda'
removed 'SAI/meta/.libs/libsaimetadata_la-saimetadata.gcda'
removed 'SAI/meta/.libs/libsaimetadata_la-saiserialize.gcno'
removed 'SAI/meta/.libs/libsaimetadata_la-saiserialize.gcda'
removed 'SAI/meta/libsaimetadata_la-saiserialize.gcno'
+ gcovr -r ./ -e '.*/SAI/.*' -e .+/json.hpp -e swss/.+ -e '.*/.libs/.*' -e '.*/debian/.*' --exclude-unreachable-branches --exclude-throw-branches -x --xml-pretty -o coverage.xml
(WARNING) Unrecognized GCOV output for /__w/1/s/meta/SaiSerialize.cpp
	  function sai_serialize_object_id[abi:cxx11](unsigned long) called 7486270 returned NAN % blocks executed 62%
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
	UnknownLineType: function sai_serialize_object_id[abi:cxx11](unsigned long) called 7486270 returned NAN % blocks executed 62%
(ERROR) Exiting because of parse errors.
	You can run gcovr with --gcov-ignore-parse-errors
	to continue anyway.
(ERROR) Trouble processing '/__w/1/s/meta/.libs/libsaimeta_la-SaiSerialize.gcda' with working directory '/__w/1/s/meta'.
Stdout of gcov was >>File 'SaiSerialize.cpp'
Lines executed:94.24% of 2100
Branches executed:93.37% of 3589
Taken at least once:53.39% of 3589
Calls executed:73.83% of 3076
Creating 'SaiSerialize.cpp##74fbe304ca213391ad9d6de89ec6b791.gcov'

File '/usr/include/c++/8/iostream'
No executable lines
No branches
No calls
Removing 'iostream##ebe1d793c3767ce0bd17617a01c13f39.gcov'

File '/usr/include/c++/8/ext/new_allocator.h'
Lines executed:13.33% of 15
No branches
No calls
Creating 'new_allocator.h##daeded247bc7390e6504e63daec329c4.gcov'

File '/usr/include/c++/8/bits/stl_pair.h'
Lines executed:0.00% of 7
Branches executed:0.00% of 2
Taken at least once:0.00% of 2
Calls executed:0.00% of 5
Creating 'stl_pair.h##177099fa84643081c2b290e0c818b6ad.gcov'

File '/usr/include/c++/8/bits/alloc_traits.h'
Lines executed:16.67% of 12
No branches
Calls executed:0.00% of 1
Creating 'alloc_traits.h##026eedf386f90d6ecabb8738c698f9ad.gcov'

File '/usr/include/c++/8/bits/stl_tree.h'
Lines executed:8.99% of 267
Branches executed:7.55% of 106
Taken at least once:3.77% of 106
Calls executed:6.96% of 158
Creating 'stl_tree.h##95c428809a353dda12311bfc69e8e2e9.gcov'

File '/usr/include/c++/8/tuple'
Lines executed:43.90% of 41
No branches
Calls executed:0.00% of 7
Creating 'tuple##1744fc293f2d8b3156ef4f0241ad195a.gcov'

File '/usr/include/c++/8/bits/move.h'
Lines executed:36.36% of 11
No branches
No calls
Creating 'move.h##7bfc359db98dc4e2c34f9209072b0c1e.gcov'

File '/usr/include/c++/8/bits/stl_iterator.h'
Lines executed:17.65% of 34
No branches
Calls executed:0.00% of 6
Creating 'stl_iterator.h##b807ef89dd675f1ba5e06014c996ed52.gcov'

File '/usr/include/c++/8/bits/stl_construct.h'
Lines executed:0.00% of 14
No branches
No calls
Creating 'stl_construct.h##6d1c215fcd4190011de16a7a5a718454.gcov'

File '/usr/include/c++/8/bits/stl_uninitialized.h'
Lines executed:56.25% of 16
No branches
Calls executed:0.00% of 3
Creating 'stl_uninitialized.h##809064d04ba38c5812bf39695b54f119.gcov'

File '/usr/include/c++/8/bits/stl_iterator_base_funcs.h'
Lines executed:100.00% of 5
No branches
No calls
Creating 'stl_iterator_base_funcs.h##d0b46cb602472c2ed0ea46b43a31f441.gcov'

File '/usr/include/c++/8/bits/stl_vector.h'
Lines executed:29.21% of 89
Branches executed:22.22% of 18
Taken at least once:16.67% of 18
Calls executed:30.36% of 56
Creating 'stl_vector.h##a87cffd70128940f27578a68ceab3f95.gcov'

File '/usr/include/c++/8/bits/allocator.h'
Lines executed:0.00% of 4
No branches
No calls
Creating 'allocator.h##0a853668aa2594c922e6bec9c124c8f0.gcov'

File '/usr/include/c++/8/ext/alloc_traits.h'
Lines executed:0.00% of 2
No branches
No calls
Creating 'alloc_traits.h##d1420fd8af385ac598f959d5ed2eecf4.gcov'

File '/usr/include/c++/8/bits/stl_iterator_base_types.h'
Lines executed:100.00% of 2
No branches
No calls
Creating 'stl_iterator_base_types.h##f9f106ff8840aaba3d70be24c7ca4af4.gcov'

File '/usr/include/c++/8/bits/unique_ptr.h'
Lines executed:80.95% of 21
No branches
No calls
Creating 'unique_ptr.h##37dc9c37b74bd9f0479c7091090029af.gcov'

File '/usr/include/c++/8/bits/basic_string.tcc'
Lines executed:0.00% of 20
Branches executed:0.00% of 6
Taken at least once:0.00% of 6
Calls executed:0.00% of 6
Creating 'basic_string.tcc##569b6d7a95a2616cf527007b5953c417.gcov'

File '/usr/include/c++/8/ext/aligned_buffer.h'
Lines executed:0.00% of 8
No branches
Calls executed:0.00% of 2
Creating 'aligned_buffer.h##707bad838921a8176b1431b8a683c449.gcov'

File '/usr/include/c++/8/ext/type_traits.h'
Lines executed:0.00% of 2
No branches
No calls
Creating 'type_traits.h##97417df1dc7c6edac85d6a82ba3d7cd0.gcov'

File '/usr/include/c++/8/bits/stl_algobase.h'
Lines executed:0.00% of 4
Branches executed:0.00% of 2
Taken at least once:0.00% of 2
No calls
Creating 'stl_algobase.h##1b85eecd0983667d1046530e38a67fff.gcov'

File '/usr/include/c++/8/bits/stl_function.h'
Lines executed:0.00% of 4
No branches
Calls executed:0.00% of 1
Creating 'stl_function.h##aead2a248f9383c7373ee5f282b7fa81.gcov'

File '/usr/include/swss/json.hpp'
Lines executed:14.02% of 1084
Branches executed:17.72% of 931
Taken at least once:9.34% of 931
Calls executed:18.14% of 711
Creating 'json.hpp##84e6af1f9d73ecea7ce324c6c364f3c3.gcov'

File '/usr/include/c++/8/bits/stl_map.h'
Lines executed:25.00% of 32
Branches executed:0.00% of 26
Taken at least once:0.00% of 26
Calls executed:11.43% of 35
Creating 'stl_map.h##1db79b43893bbf67b5b0bcab9ae8d56b.gcov'

File '/usr/include/c++/8/bits/vector.tcc'
Lines executed:62.86% of 35
Branches executed:0.00% of 2
Taken at least once:0.00% of 2
Calls executed:0.00% of 5
Creating 'vector.tcc##a1523c4833758488fcc5a003d6cfa34d.gcov'

File '/usr/include/c++/8/initializer_list'
Lines executed:100.00% of 5
No branches
No calls
Creating 'initializer_list##ab946e93d816dd47dbbbe86cbd9f00d2.gcov'

File '/usr/include/c++/8/bits/basic_string.h'
Lines executed:0.00% of 35
Branches executed:0.00% of 10
Taken at least once:0.00% of 10
Calls executed:0.00% of 29
Creating 'basic_string.h##6bd0577e5b79b7dfe2cfcfd525fc2595.gcov'

File '/usr/include/c++/8/bits/std_function.h'
Lines executed:0.00% of 22
Branches executed:0.00% of 8
Taken at least once:0.00% of 8
Calls executed:0.00% of 13
Creating 'std_function.h##b4e73a000b1992c668c3757f8f9b98eb.gcov'

File '/usr/include/c++/8/cmath'
Lines executed:0.00% of 2
No branches
No calls
Creating 'cmath##5936c491ca619464dcb98c204cc9b20b.gcov'

File 'sai_serialize.h'
Lines executed:100.00% of 3
No branches
No calls
Creating 'sai_serialize.h##9ef1a700e0df47b68acd861e55fc2d68.gcov'

File '/usr/include/c++/8/ext/string_conversions.h'
Lines executed:0.00% of 6
Branches executed:0.00% of 4
Taken at least once:0.00% of 4
Calls executed:0.00% of 5
Creating 'string_conversions.h##8d705deac381b99a6c3cfc637ac1030b.gcov'

File '/usr/include/c++/8/limits'
Lines executed:100.00% of 1
No branches
No calls
Creating 'limits##797bfbd81186de497e7232d3d188e23a.gcov'

File '/usr/include/c++/8/iomanip'
Lines executed:0.00% of 2
No branches
No calls
Creating 'iomanip##a65d94a7a8dd7af5382049addcbf86dc.gcov'

File '/usr/include/c++/8/bits/ios_base.h'
Lines executed:0.00% of 22
No branches
Calls executed:0.00% of 9
Creating 'ios_base.h##63195494947582cf9b52c40c8e8f3728.gcov'

File '/usr/include/c++/8/bits/char_traits.h'
Lines executed:0.00% of 6
Branches executed:0.00% of 2
Taken at least once:0.00% of 2
No calls
Creating 'char_traits.h##d542261603d54cac1c1dd2fe3c479ffc.gcov'

File '/usr/include/c++/8/new'
Lines executed:0.00% of 3
No branches
No calls
Creating 'new##70213a621f1a15ae0aa78c28050996bc.gcov'

<< End of stdout
Stderr of gcov was >><< End of stderr
Current processed gcov file was '/__w/1/s/meta/SaiSerialize.cpp##74fbe304ca213391ad9d6de89ec6b791.gcov'.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 343, in process_datafile
    chdir=wd,
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 163, in process_gcov_data
    flags=parser_flags,
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 404, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 552, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 353, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 836, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: function sai_serialize_object_id[abi:cxx11](unsigned long) called 7486270 returned NAN % blocks executed 62%
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 343, in process_datafile
    chdir=wd,
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 163, in process_gcov_data
    flags=parser_flags,
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 404, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 552, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 353, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 836, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: function sai_serialize_object_id[abi:cxx11](unsigned long) called 7486270 returned NAN % blocks executed 62%
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.2', 'console_scripts', 'gcovr')())
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/__main__.py", line 317, in main
    covdata = collect_coverage_from_gcov(options)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/__main__.py", line 376, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/workers.py", line 171, in __exit__
    self.wait()
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/__main__.py", line 376, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 343, in process_datafile
    chdir=wd,
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov.py", line 163, in process_gcov_data
    flags=parser_flags,
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 404, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 552, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 353, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
  File "/usr/local/lib/python3.7/dist-packages/gcovr-5.2-py3.7.egg/gcovr/gcov_parser.py", line 836, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: function sai_serialize_object_id[abi:cxx11](unsigned long) called 7486270 returned NAN % blocks executed 62%
```

**To Reproduce**
* https://github.com/sonic-net/sonic-sairedis/pull/1197/checks?check_run_id=10929622668

**Expected behavior**
No parser errors

**Screenshots**
* N/A

**Desktop (please complete the following information):**
 - OS: `Debian`
 - GCC version: `gcc (Debian 10.2.1-6) 10.2.1 20210110`
 - GCOVR version: `gcovr 5.2`

**Additional context**
* N/A

**Comment by latk** [comment]
Thank you for this report! This was fixed in #651 and will be part of the next gcovr release. In the meantime, you can:

* use the `--gcov-ignore-parse-errors` to continue despite the error
* install the gcovr development version directly from GitHub, see <https://gcovr.com/en/master/installation.html>. You can also pin a specific commit if desired.
