### ISSUE TITLE
Unrecognized GCOV output with gcc 13: branch  0 never executed (fallthrough)

### ISSUE THREAD

**Issue by smcv** [gcovr/gcovr#710]
**Describe the bug**
When running CI for https://gitlab.freedesktop.org/accountsservice/accountsservice on Fedora rawhide (rolling release), using gcc 13.0.1-0.2.fc38 and gcovr 5.2-1.fc38, gcovr outputs:

```
FAILED: meson-internal__coverage 
/usr/bin/meson --internal coverage /home/user/accountsservice-branches /home/user/accountsservice-branches/subprojects /home/user/accountsservice-branches/_build /home/user/accountsservice-branches/_build/meson-logs
(WARNING) Unrecognized GCOV output for /home/user/accountsservice-branches/src/extensions.c
	  branch  1 never executed (fallthrough)
	  branch  0 never executed (fallthrough)
	  branch  2 never executed (fallthrough)
	  branch  4 never executed (fallthrough)
	  branch  6 never executed (fallthrough)
	  branch  0 never executed (fallthrough)
	  branch  3 never executed (fallthrough)
	  branch  0 never executed (fallthrough)
	  branch  0 never executed (fallthrough)
	  branch  2 never executed (fallthrough)
	  branch  1 never executed (fallthrough)
	  branch  1 never executed (fallthrough)
	  branch  0 never executed (fallthrough)
	  branch  0 never executed (fallthrough)
	  branch  3 never executed (fallthrough)
	  branch  2 never executed (fallthrough)
	  branch  0 never executed (fallthrough)
	  branch  1 never executed (fallthrough)
	  branch  3 never executed (fallthrough)
	  branch  2 never executed (fallthrough)
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
	UnknownLineType: branch  1 never executed (fallthrough)
(etc.)
```

I think this might be because the gcov from gcc 13 added ` (fallthrough)` at the end of these lines?

**To Reproduce**
Sorry, I don't currently have a smaller reproducer than the CI for https://gitlab.freedesktop.org/accountsservice/accountsservice/-/merge_requests/117 (I do not operate that CI and didn't choose to run it on gcc 13)

**Expected behavior**
`branch  1 never executed (fallthrough)` should probably be parsed as equivalent to `branch  1 never executed` which gcovr seems to handle already?

**Desktop (please complete the following information):**
 - OS: Fedora rawhide (Fedora 38 alpha)
 - GCC version: 13.0.1-0.2.fc38
 - GCOVR version: 5.2-1.fc38
 - Project directory layout: sorry, I don't know what this means. It's a relatively ordinary Meson build?

**Comment by dev-zero** [comment]
I see a very similar thing with gcc-12 on macOS:

```
Creating 'dbcsr_mm_multrec.F##078e76838976298073c9900770935f33.gcov'

Lines executed:69.12% of 285
<< End of stdout
Stderr of gcov was >><< End of stderr
Current processed gcov file was '/Users/tiziano/Projects/cp2k/dbcsr/dbcsr_mm_multrec.F##078e76838976298073c9900770935f33.gcov'.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "/Users/tiziano/.local/pipx/venvs/gcovr/lib/python3.10/site-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/Users/tiziano/.local/pipx/venvs/gcovr/lib/python3.10/site-packages/gcovr/gcov.py", line 328, in process_datafile
    done = run_gcov_and_process_files(
  File "/Users/tiziano/.local/pipx/venvs/gcovr/lib/python3.10/site-packages/gcovr/gcov.py", line 561, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/Users/tiziano/.local/pipx/venvs/gcovr/lib/python3.10/site-packages/gcovr/gcov.py", line 144, in process_gcov_data
    coverage, source_lines = parse_coverage(
  File "/Users/tiziano/.local/pipx/venvs/gcovr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 328, in parse_coverage
    _report_lines_with_errors(
  File "/Users/tiziano/.local/pipx/venvs/gcovr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 494, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/Users/tiziano/.local/pipx/venvs/gcovr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 301, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
  File "/Users/tiziano/.local/pipx/venvs/gcovr/lib/python3.10/site-packages/gcovr/gcov_parser.py", line 686, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: branch  3 taken -1
```

The relevant `.gcov` looks like this:

```
function __dbcsr_mm_multrec_MOD_dbcsr_mm_multrec_multiply called 19399 returned 100% blocks executed 64%
    19399:  263:   SUBROUTINE dbcsr_mm_multrec_multiply(this, left, right, flop, &
   19399*:  264:                                        a_norms, b_norms, k_sizes)
branch  0 taken 19399 (fallthrough)
branch  1 taken 0
branch  2 taken 19400 (fallthrough)
branch  3 taken -1
        -:  265:      !! Multiplies two DBCSR matrices using recursive algorithm
        -:  266:      !! This routine sets up the multiplication.  Specifically, it <ul>
        -:  267:      !! <li> verifies input sanity
        -:  268:      !! <li> converts everything into "local indexing"
        -:  269:      !! </ul>
```

**Comment by Spacetown** [comment]
@smvc Yes, this was a patch from my side because this information was missing on branches which were not executed. Need to check this.

@dev-zero Your problem is a bug in GCC where the counters are corrupted and shown as negative values. This problem is handled in #701 which isn't merged yet.
