### ISSUE TITLE
Error: system cannot find the file specified

### ISSUE THREAD

**Issue by hsdk123** [gcovr/gcovr#797]
Hi, I get the following error and am stuck - would anyone know what's happening?
(OS: Windows)

```
C:\Users\daego\Desktop\Projects\Light.vn-core\core (master -> origin)
λ gcovr.exe --verbose -r C:/Users/daego/Desktop/Projects/Light.vn-core/core --object-directory C:/Users/daego/Desktop/Projects/Light.vn-core/core/out/build/x64-Release-Clang-Cored
(DEBUG) File system is case insensitive.
(DEBUG) Filters for --root: (1)
(DEBUG)  - re.compile('^C:\\\\Users\\\\daego\\\\Desktop\\\\Projects\\\\Light\\.vn\\-core\\\\core\\\\')
(DEBUG) Filters for --filter: (1)
(DEBUG)  - DirectoryPrefixFilter(C:/Users/daego/Desktop/Projects/Light\.vn\-core/core/)
(DEBUG) Filters for --exclude: (0)
(DEBUG) Filters for --gcov-filter: (1)
(DEBUG)  - AlwaysMatchFilter()
(DEBUG) Filters for --gcov-exclude: (0)
(DEBUG) Filters for --gcov-exclude-directories: (0)
(DEBUG) Scanning directory . for gcda/gcno files...
(DEBUG) Found 514 files (and will process 268)
(DEBUG) Scanning directory out\build\x64-Release-Clang-Cored for gcda/gcno files...
(DEBUG) Found 514 files (and will process 268)
(DEBUG) Pool started with 1 threads
(DEBUG) Processing file: C:\Users\daego\Desktop\Projects\Light.vn-core\core\out\build\x64-Release-Clang-Cored\src\CMakeFiles\MyCore.dir\Code\80.Obj\System\Grid\Grid.cpp.gcda
(DEBUG) Running gcov: 'gcov --help' in '.'
(ERROR) Trouble processing 'C:/Users/daego/Desktop/Projects/Light.vn-core/core/out/build/x64-Release-Clang-Cored/src/CMakeFiles/MyCore.dir/Code/80.Obj/System/Grid/Grid.cpp.gcda' with working directory 'C:\\Users\\daego\\Desktop\\Projects\\Light.vn-core\\core\\out\\build\\x64-Release-Clang-Cored'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\workers.py", line 80, in worker
    work(*args, **kwargs)
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 402, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 623, in run_gcov_and_process_files
    gcov_cmd.identify_and_cache_capabilities()
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 500, in identify_and_cache_capabilities
    if self.__check_gcov_help_content("--demangled-names"):
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 538, in __check_gcov_help_content
    if option in self.__get_help_output():
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 522, in __get_help_output
    gcov_process = self.__get_gcov_process(
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 557, in __get_gcov_process
    return subprocess.Popen(
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\workers.py", line 80, in worker
    work(*args, **kwargs)
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 402, in process_datafile
    done = run_gcov_and_process_files(
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 623, in run_gcov_and_process_files
    gcov_cmd.identify_and_cache_capabilities()
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 500, in identify_and_cache_capabilities
    if self.__check_gcov_help_content("--demangled-names"):
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 538, in __check_gcov_help_content
    if option in self.__get_help_output():
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 522, in __get_help_output
    gcov_process = self.__get_gcov_process(
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\site-packages\gcovr\formats\gcov\read.py", line 557, in __get_gcov_process
    return subprocess.Popen(
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\daego\appdata\local\programs\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
(ERROR) Error occurred while reading reports:
        [WinError 2] The system cannot find the file specified
```

**Comment by Spacetown** [comment]
Have you tried the option `--verbose` as mentioned? For me it seems that the `gcov.exe` is not found.

**Comment by hsdk123** [comment]
> Have you tried the option `--verbose` as mentioned? For me it seems that the `gcov.exe` is not found.

Yes, as in the logs
```
gcovr.exe --verbose -r C:/Users/daego/Desktop/Projects/Light.vn-core/core --object-directory C:/Users/daego/Desktop/Projects/Light.vn-core/core/out/build/x64-Release-Clang-Cored`

**Comment by Spacetown** [comment]
> 

That's interesting. What exe do you use? If it is generated with our development environment on your own there shouldn't be pathst to your installation in the backtrace. Another executable isn't provided by us.

Nevertheless there should be more information in the output. I'm interested in the command which gcov is executed and if the executable exists in your system.

**Comment by Spacetown** [comment]
No response.
