### ISSUE TITLE
Parser fails with 'gcovr.gcov_parser.UnknownLineType: branch  8 never executed (fallthrough)'

### ISSUE THREAD

**Issue by lleoha** [gcovr/gcovr#833]
**Describe the bug**
gcovr fails to parse report

**To Reproduce**
1. build c++ test with (`--coverage` flag)
2. . run it
3. run gcovr

**Expected behavior**
No errors

**Screenshots**
```
$ gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o build_testcoverage/coverage.xml --root . 
 build_testcoverage
(WARNING) Unrecognized GCOV output for /builds/leoha/ellip/test/main.cpp
	  branch  8 never executed (fallthrough)
	  branch  9 never executed (throw)
	  branch 12 never executed (fallthrough)
	  branch 13 never executed (throw)
	  branch 15 never executed (fallthrough)
	  branch 16 never executed (throw)
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
	UnknownLineType: branch  8 never executed (fallthrough)
(WARNING) Exception during parsing:
	UnknownLineType: branch  9 never executed (throw)
(WARNING) Exception during parsing:
	UnknownLineType: branch 12 never executed (fallthrough)
(WARNING) Exception during parsing:
	UnknownLineType: branch 13 never executed (throw)
(WARNING) Exception during parsing:
	UnknownLineType: branch 15 never executed (fallthrough)
(WARNING) Exception during parsing:
	UnknownLineType: branch 16 never executed (throw)
(ERROR) Exiting because of parse errors.
	You can run gcovr with --gcov-ignore-parse-errors
	to continue anyway.
(ERROR) Trouble processing '/builds/leoha/ellip/build_testcoverage/CMakeFiles/tests.dir/test/main.cpp.gcda' with working directory '/builds/leoha/ellip'.
Stdout of gcov was >>File '/builds/leoha/ellip/test/main.cpp'
Lines executed:100.00% of 15
Branches executed:40.00% of 10
Taken at least once:20.00% of 10
Calls executed:47.06% of 17
Creating 'main.cpp##465e75c83a0e60bdf37ad908863eceaa.gcov'
File '/usr/include/gtest/internal/gtest-internal.h'
Lines executed:85.71% of 21
Branches executed:34.78% of 46
Taken at least once:17.39% of 46
Calls executed:30.00% of 30
Creating 'gtest-internal.h##c20d41c1f321958c2e0c92e9c5acab29.gcov'
File '/usr/local/include/c++/13.2.0/bits/new_allocator.h'
Lines executed:87.50% of 8
Branches executed:100.00% of 2
Taken at least once:50.00% of 2
Calls executed:66.67% of 3
Creating 'new_allocator.h##09500486fa81aaf02a4ac78b985efe02.gcov'
File '/usr/local/include/c++/13.2.0/bits/allocator.h'
Lines executed:54.55% of 11
Branches executed:66.67% of 6
Taken at least once:33.33% of 6
Calls executed:57.14% of 7
Creating 'allocator.h##7530b3b221f7719[212](https://gitlab.com/leoha/ellip/-/jobs/5152810261#L212)64b7b98f4348fa.gcov'
File '/usr/local/include/c++/13.2.0/bits/move.h'
Lines executed:68.75% of 32
No branches
Calls executed:66.67% of 3
Creating 'move.h##2ad71f5ed2d90c573b9df126e86f5463.gcov'
File '/usr/include/gtest/gtest-printers.h'
Lines executed:0.00% of 28
Branches executed:0.00% of 6
Taken at least once:0.00% of 6
Calls executed:0.00% of 14
Creating 'gtest-printers.h##162053d178388e5a4f3019c80e9120d3.gcov'
File '/usr/local/include/c++/13.2.0/tuple'
Lines executed:60.32% of 63
No branches
Calls executed:55.56% of 27
Creating 'tuple##4871c106f2635775c5e13bda1a3160ae.gcov'
File '/usr/local/include/c++/13.2.0/bits/ptr_traits.h'
Lines executed:100.00% of 6
No branches
Calls executed:100.00% of 2
Creating 'ptr_traits.h##563e5e869999c6e5061d0b446ecef478.gcov'
File '/usr/include/gtest/gtest.h'
Lines executed:38.46% of 13
Branches executed:25.00% of 8
Taken at least once:12.50% of 8
Calls executed:27.27% of 11
Creating 'gtest.h##511c3db1ef0ef52ebbd69e985e8992b8.gcov'
File '/usr/local/include/c++/13.2.0/bits/basic_string.h'
Lines executed:91.67% of 72
Branches executed:75.00% of 24
Taken at least once:50.00% of 24
Calls executed:82.50% of 40
Creating 'basic_string.h##5b7363fa475730eca3e3cf6cc17db6be.gcov'
File '/usr/local/include/c++/13.2.0/bits/alloc_traits.h'
Lines executed:100.00% of 4
No branches
No calls
Creating 'alloc_traits.h##30384a0d1f3e367f455a1ebc1f6bd462.gcov'
File '/usr/local/include/c++/13.2.0/bits/unique_ptr.h'
Lines executed:27.27% of 44
Branches executed:25.00% of 8
Taken at least once:12.50% of 8
Calls executed:10.00% of 20
Creating 'unique_ptr.h##62180d3cd31d8088b519144bbe74946e.gcov'
File '/usr/local/include/c++/13.2.0/bits/basic_string.tcc'
Lines executed:95.45% of 44
Branches executed:100.00% of 20
Taken at least once:60.00% of 20
Calls executed:83.33% of 24
Creating 'basic_string.tcc##4cb351f8cc0aba7f710f8595c212a5d1.gcov'
File '/usr/local/include/c++/13.2.0/bits/stl_iterator_base_types.h'
Lines executed:100.00% of 1
No branches
No calls
Creating 'stl_iterator_base_types.h##de730e0e5efe27faf58513a657687caa.gcov'
File '/usr/local/include/c++/13.2.0/bits/stl_iterator_base_funcs.h'
Lines executed:100.00% of 3
No branches
No calls
Creating 'stl_iterator_base_funcs.h##fbefda21d6a7bc608c2bcb7bebb23f5b.gcov'
File '/usr/local/include/c++/13.2.0/bits/char_traits.h'
Lines executed:38.71% of 31
Branches executed:50.00% of 16
Taken at least once:31.25% of 16
Calls executed:33.33% of 9
Creating 'char_traits.h##8cf1dbbf7d040878bb42f587626c9550.gcov'
File '/usr/local/include/c++/13.2.0/ext/alloc_traits.h'
Lines executed:100.00% of 1
No branches
No calls
Creating 'alloc_traits.h##3bd083b9ec458ea7c87601c56f2ab1d2.gcov'
File '/usr/local/include/c++/13.2.0/bits/stl_construct.h'
Lines executed:0.00% of 2
No branches
Calls executed:0.00% of 2
Creating 'stl_construct.h##0247e1fddbd89963c51c53e799fdd35c.gcov'
File '/builds/leoha/ellip/src/uint/uint_impl.h'
Lines executed:93.10% of 29
Branches executed:100.00% of 18
Taken at least once:66.67% of 18
Calls executed:100.00% of 18
Creating 'uint_impl.h##d1140268d4860e8a1075de2ec5613ab6.gcov'
File '/usr/local/include/c++/13.2.0/array'
Lines executed:100.00% of 8
No branches
No calls
Creating 'array##40fa7e1879d101d39c11f3677df78d85.gcov'
File '/builds/leoha/ellip/src/uint/uint.h'
Lines executed:100.00% of 1
No branches
No calls
Creating 'uint.h##6eb3ebddc0a512b73d09a1509304f72d.gcov'
File '/usr/local/include/c++/13.2.0/bits/stl_pair.h'
Lines executed:100.00% of 15
No branches
Calls executed:100.00% of 11
Creating 'stl_pair.h##ab8f6fa9d74ff4afd32813a3814ac793.gcov'
File '/usr/include/gtest/gtest-assertion-result.h'
Lines executed:25.00% of 4
Branches executed:0.00% of 2
Taken at least once:0.00% of 2
Calls executed:0.00% of 4
Creating 'gtest-assertion-result.h##97b4cbf37ff9502dd95413f11ba0cd3a.gcov'
File '/usr/include/gtest/gtest-message.h'
No executable lines
No branches
No calls
Removing 'gtest-message.h##918c[214](https://gitlab.com/leoha/ellip/-/jobs/5152810261#L214)5cf91b3[236](https://gitlab.com/leoha/ellip/-/jobs/5152810261#L236)39f638bd8fd9aac.gcov'
File '/usr/include/gtest/internal/gtest-port.h'
Lines executed:0.00% of 1
No branches
No calls
Creating 'gtest-port.h##cc929cd956db0196528ac72ea5445c17.gcov'
File '/usr/local/include/c++/13.2.0/compare'
Lines executed:100.00% of 2
Branches executed:100.00% of 2
Taken at least once:50.00% of 2
No calls
Creating 'compare##11d9b8ddbf4192d70c014fcbc16bc2c3.gcov'
File '/usr/local/include/c++/13.2.0/type_traits'
Lines executed:100.00% of 2
No branches
No calls
Creating 'type_traits##79b6f4861dfe62051521065c2c8c29de.gcov'
File '/usr/local/include/c++/13.2.0/new'
Lines executed:0.00% of 2
No branches
No calls
Creating 'new##9ded0db8b624d02ae1c0fd1036f8c4ec.gcov'
File '/usr/local/include/c++/13.2.0/x86_64-linux-gnu/bits/c++config.h'
Lines executed:100.00% of 2
No branches
No calls
Creating 'c++config.h##ed0f9f509308aab69e0fd07da946[304](https://gitlab.com/leoha/ellip/-/jobs/5152810261#L304)4.gcov'
Lines executed:67.96% of 465
<< End of stdout
Stderr of gcov was >><< End of stderr
Current processed gcov file was '/builds/leoha/ellip/main.cpp##465e75c83a0e60bdf37ad908863eceaa.gcov'.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line 157, in process_gcov_data
    coverage = parse_coverage(
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 404, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 552, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 353, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 836, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: branch  8 never executed (fallthrough)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line 157, in process_gcov_data
    coverage = parse_coverage(
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 404, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 552, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 353, in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 836, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: branch  8 never executed (fallthrough)
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.2', 'console_scripts', 'gcovr')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/__main__.py", line [317](https://gitlab.com/leoha/ellip/-/jobs/5152810261#L317), in main
    covdata = collect_coverage_from_gcov(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/__main__.py", line 369, in collect_coverage_from_gcov
    with Workers(
  File "/usr/lib/python3/dist-packages/gcovr/workers.py", line 171, in __exit__
    self.wait()
  File "/usr/lib/python3/dist-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3/dist-packages/gcovr/__main__.py", line 376, in collect_coverage_from_gcov
    contexts = pool.wait()
               ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/usr/lib/python3/dist-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line [337](https://gitlab.com/leoha/ellip/-/jobs/5152810261#L337), in process_datafile
    done = run_gcov_and_process_files(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/lib/python3/dist-packages/gcovr/gcov.py", line 157, in process_gcov_data
    coverage = parse_coverage(
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 404, in parse_coverage
    _report_lines_with_errors(lines_with_errors, context)
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 552, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line [353](https://gitlab.com/leoha/ellip/-/jobs/5152810261#L353), in parse_coverage
    tokenized_lines.append((_parse_line(raw_line), raw_line))
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gcovr/gcov_parser.py", line 836, in _parse_line
    raise UnknownLineType(line)
gcovr.gcov_parser.UnknownLineType: branch  8 never executed (fallthrough)
```

**Desktop (please complete the following information):**
 - GCC version [e.g. MinGW 8.1.0]
 - GCOVR version [e.g. 4.2]
 - Project directory layout:
   - Roots
   - Object directories

**Additional context**
```
root@ab810ec847bd:/# gcc --version
gcc (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@ab810ec847bd:/# gcov --version
gcov (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@ab810ec847bd:/# gcovr --version
gcovr 5.2

Copyright (c) 2013-2022 the gcovr authors
Copyright (c) 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
```

**Comment by lleoha** [comment]
I used not the latest version.
