### ISSUE TITLE
Parsing error: AssertionError: lineno 365 is negative : -1

### ISSUE THREAD

**Issue by Vladyyy** [gcovr/gcovr#847]
**Describe the bug**
gcov failing with the error below, I have redacted some of the paths, so they might not be accurate
```
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   /local/home/vlad/workspace/src/XXX.cpp##8df0470d88d20089637d0c15aa9b1e2b.gcov
  currdir      /local/home/vlad/workspace/src/TestRunner
  root         /local/home/vlad/workspace/src/AsyncFramework/src
  starting_dir /local/home/vlad/workspace/src/TestRunner
  obj_dir      None
  gcda_fname   /local/home/vlad/workspace/gcda_data/XXX.gcda
  --> fname    /local/home/vlad/workspace/src/XXX.cpp

(DEBUG) Parsing coverage data for file /local/home/vlad/workspace/src/XXX.cpp
(WARNING) Ignoring negative hits in line 'branch 10 taken -1'.
(WARNING) Unrecognized GCOV output for /local/home/vlad/workspace/src/XXX.cpp
	         -1:  365:            finish(0);
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
	AssertionError: lineno is negative 365: -1
(ERROR) Exiting because of parse errors.
	You can run gcovr with --gcov-ignore-parse-errors
	to continue anyway.
(ERROR) Trouble processing '/local/home/vlad/workspace/gcda_data/XXX.gcda' with working directory '/local/home/vlad/workspace/src'.
S
	
	Stderr of gcov was >><< End of stderr

Current processed gcov file was 'XXX.cpp##8df0470d88d20089637d0c15aa9b1e2b.gcov'.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/workers.py", line 80, in worker
    work(*args, **kwargs)
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/gcov.py", line 323, in process_datafile
    done = run_gcov_and_process_files(
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/gcov.py", line 564, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/gcov.py", line 140, in process_gcov_data
    coverage, source_lines = parse_coverage(
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 355, in parse_coverage
    _report_lines_with_errors(
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 521, in _report_lines_with_errors
    raise errors[0]  # guaranteed to have at least one exception
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 336, in parse_coverage
    state = _gather_coverage_from_line(
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 406, in _gather_coverage_from_line
    insert_line_coverage(coverage, LineCoverage(lineno, count=raw_count))
  File "/local/home/vlad/workspace/runtime/lib/python3.8/site-packages/gcovr/coverage.py", line 272, in __init__
    assert count >= 0, f"lineno is negative {lineno}: {count}"
AssertionError: lineno is negative 365: -1

```

I have changed the assert locally to log the lineno and count

The code snipptet flagged above looks like this:
```
364         if (!should_run()) {
365             finish(0);
366             return;
```

**To Reproduce**
```
 gcovr  --verbose --gcov-ignore-parse-errors negative_hits.warn --root /local/home/vlad/workspace/src /local/home/tudosevt/workspace/gcda_data
 ```

**Desktop (please complete the following information):**
gcovr 6.

**Comment by Spacetown** [comment]
This is a bug in gcov and we can't workaround this. Please see also #583.

**Comment by Vladyyy** [comment]
Isn't `--gcov-ignore-parse-errors negative_hits.warn` be a workaround for this issue? The invocation above is with this option provided

**Comment by latk** [comment]
I see. Negative hit handling has so far only been implemented for branch coverage data.

Here, we have a negative counter on line coverage. Our gcov parser understands this syntax, but does not recognize the problem. The coverage data model classes do reject this though, ensuring integrity of the reported coverage statistics.

**Comment by Spacetown** [comment]
Oh, my fault. I'm already working on it. @latk Shall we add the check only to the lines where the error already occurred or to all lines whith hit values?

**Comment by Spacetown** [comment]
@Vladyyy Please can you check the branch from the linked PR and leave a review comment?
