### ISSUE TITLE
Still getting gcovr failure due to gcov return value 6.

### ISSUE THREAD

**Issue by sawatts** [gcovr/gcovr#962]
# Describe the bug

We started seeing **gcovr** failing due to _"GCOV returncode was 6"_ following a company update to GCC12.  Looking at the **gcovr** changelog, this was addressed in version 7.0.  Therefore we have updated our **gcovr** to the latest (7.2) version.

However the issue remains.

# To Reproduce

1. Run **gcovr** against the results of an instrumented build, where **gcov** will return error code 6 for some aspect.
2. Expect **gcovr** to complete successfully.

# Expected behavior

**gcovr** ignores **gcov** return code 6 and does not treat it as an error.

# Actual behavior

Command as issued:
```sh
${ROOT}/bin/gcovr3.8
	--gcov-executable ${ROOT}/bin/gcov
	--xml ${WORKSPACE}/.logs/coverage-cpp.xml
	--root ${WORKSPACE}
	--exclude '.*/CMakeFiles/.*'
	--gcov-ignore-errors=no_working_dir_found
```

Error log:
```
(ERROR) Trouble processing '${WPRKSPACE}/.coverity/coverage/gcno/1/8/5/b/c340722aa12e93d8874740cb2567.gcno' with working directory '/bb/jenkins_work'.
Stdout of gcov was >>None<< End of stdout
Stderr of gcov was >>None<< End of stderr
Current processed gcov file was None.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "${ROOT}/lib/python3.8/site-packages/gcovr/workers.py", line 80, in worker
    work(*args, **kwargs)
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 323, in process_datafile
    done = run_gcov_and_process_files(
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 536, in run_gcov_and_process_files
    out, err = gcov_cmd.run_with_args(
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 519, in run_with_args
    raise RuntimeError(f"GCOV returncode was {gcov_process.returncode}.")
RuntimeError: GCOV returncode was 6.
Traceback (most recent call last):
  File "${ROOT}/lib/python3.8/site-packages/gcovr/workers.py", line 80, in worker
    work(*args, **kwargs)
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 323, in process_datafile
    done = run_gcov_and_process_files(
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 536, in run_gcov_and_process_files
    out, err = gcov_cmd.run_with_args(
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 519, in run_with_args
    raise RuntimeError(f"GCOV returncode was {gcov_process.returncode}.")
RuntimeError: GCOV returncode was 6.
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "${ROOT}/bin/gcovr3.8", line 33, in <module>
    sys.exit(load_entry_point('gcovr==6.0', 'console_scripts', 'gcovr')())
  File "${ROOT}/lib/python3.8/site-packages/gcovr/__main__.py", line 328, in main
    covdata = collect_coverage_from_gcov(options)
  File "${ROOT}/lib/python3.8/site-packages/gcovr/__main__.py", line 387, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "${ROOT}/lib/python3.8/site-packages/gcovr/workers.py", line 173, in __exit__
    self.wait()
  File "${ROOT}/lib/python3.8/site-packages/gcovr/workers.py", line 164, in wait
    raise self.exceptions[0][1]
  File "${ROOT}/lib/python3.8/site-packages/gcovr/__main__.py", line 387, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "${ROOT}/lib/python3.8/site-packages/gcovr/workers.py", line 164, in wait
    raise self.exceptions[0][1]
  File "${ROOT}/lib/python3.8/site-packages/gcovr/workers.py", line 80, in worker
    work(*args, **kwargs)
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 323, in process_datafile
    done = run_gcov_and_process_files(
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 536, in run_gcov_and_process_files
    out, err = gcov_cmd.run_with_args(
  File "${ROOT}/lib/python3.8/site-packages/gcovr/gcov.py", line 519, in run_with_args
    raise RuntimeError(f"GCOV returncode was {gcov_process.returncode}.")
RuntimeError: GCOV returncode was 6.
```

# Desktop (please complete the following information)

- OS:
    - Red Hat Enterprise Linux Server release 7.6 & 7.9
    - `Linux xxx 3.10.0-957.35.2.el7.x86_64 #1 SMP Wed Sep 18 05:51:28 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux`
    - `Linux xxx 3.10.0-1160.80.1.el7.x86_64 #1 SMP Sat Oct 8 18:13:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- GCC version
    - gcc (GCC) 12.1.1 20220628 (Red Hat 12.1.1-3)
    - gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
- GCOVR version
    - gcovr 7.2
- Project directory layout:
  - Jenkins workspace

# Additional context

Looking at the changeset, it appears that **gcov** return code 6 is suppressed by **gcovr** _iff_ the `gcov --help` output contains the string "LLVM".  This does not appear when we run `gcov --help` from our installation.

Wouldn't reading the version be a better approach?

I suspect that the GCOV return value 6 is due to the coverage data file being from a source file under an excluded folder.  This build uses **coverity** to add coverage instrumentation, and this also catalogues the coverage data files under its own location.  Either way, this was previously working with pre-GCC12.

**Comment by Spacetown** [comment]
We ignore the exit code 6 if the output does NOT contain LLVM because a LLVM based gcov doesn't use exit code 6 if writing an output file is failing. According to your log you're still using version 6 of gcovr which doesn't ignore exit code 6, this was introduced with version 7.0.

```
Traceback (most recent call last):
  File "${ROOT}/bin/gcovr3.8", line 33, in <module>
    sys.exit(load_entry_point('gcovr==6.0', 'console_scripts', 'gcovr')())
```

**Comment by sawatts** [comment]
The version being used reports as 7.2:
```sh
$ opt/bb/bin/gcovr3.8 --version
gcovr 7.2
```

It was previously version 6.0, but an internal ticket was raised to re-release the latest version to our development stack.

**Comment by Spacetown** [comment]
Do you have a complete log? The previous one clearly used the 6.0.

**Comment by sawatts** [comment]
I am rerunning our build.

**Comment by sawatts** [comment]
I can confirm it is working as expected.

The test build was using a different reference root, so was using the old GCOVR.  Rebuilding and ensuring that it is using the new GCOVR successfully generates coverage reports.

False Negative.
