### ISSUE TITLE
v8.0 - key error (on Windows)

### ISSUE THREAD

**Issue by ReenigneArcher** [gcovr/gcovr#984]
Running gcovr with the following parameters

```bash
python -m pip install gcovr
python -m gcovr -r .. \
  --exclude-noncode-lines \
  --exclude-throw-branches \
  --exclude-unreachable-branches \
  --exclude '.*_deps/.*' \
  --exclude '.*tests/.*' \
  --exclude '.*third-party/.*' \
  --xml-pretty \
  -o coverage.xml
```

pip install logs:
```
Collecting gcovr
  Downloading gcovr-8.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting jinja2 (from gcovr)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting lxml (from gcovr)
  Downloading lxml-5.3.0-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Collecting colorlog (from gcovr)
  Downloading colorlog-6.8.2-py3-none-any.whl.metadata (10 kB)
Collecting pygments>=2.13.0 (from gcovr)
  Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting colorama (from colorlog->gcovr)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting MarkupSafe>=2.0 (from jinja2->gcovr)
  Downloading MarkupSafe-3.0.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Downloading gcovr-8.0-py2.py3-none-any.whl (213 kB)
Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 1.2/1.2 MB 15.0 MB/s eta 0:00:00
Downloading colorlog-6.8.2-py3-none-any.whl (11 kB)
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading lxml-5.3.0-cp311-cp311-win_amd64.whl (3.8 MB)
   ---------------------------------------- 3.8/3.8 MB 45.5 MB/s eta 0:00:00
Downloading MarkupSafe-3.0.1-cp311-cp311-win_amd64.whl (15 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: pygments, MarkupSafe, lxml, colorama, jinja2, colorlog, gcovr
  WARNING: The script pygmentize.exe is installed in 'C:\hostedtoolcache\windows\Python\3.11.9\x64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script gcovr.exe is installed in 'C:\hostedtoolcache\windows\Python\3.11.9\x64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed MarkupSafe-3.0.1 colorama-0.4.6 colorlog-6.8.2 gcovr-8.0 jinja2-3.1.4 lxml-5.3.0 pygments-2.18.0
```

I get the following error (https://github.com/LizardByte/Sunshine/actions/runs/11246344220/job/31268055119?pr=3276#step:11:52):
```
(INFO) Reading coverage data...

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 81, in worker
    work(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 566, in process_datafile
    done = run_gcov_and_process_files(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 922, in run_gcov_and_process_files
    process_gcov_json_data(gcov_filename, covdata, options)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 294, in process_gcov_json_data
    apply_all_exclusions(file_cov, lines=encoded_source_lines, options=options)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\exclusions\__init__.py", line 109, in apply_all_exclusions
    remove_internal_functions(filecov)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\exclusions\__init__.py", line 136, in remove_internal_functions
    filecov.functions.pop(function.demangled_name)
KeyError: '__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > config::skip_list<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)'
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 81, in worker
    work(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 566, in process_datafile
    done = run_gcov_and_process_files(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 922, in run_gcov_and_process_files
    process_gcov_json_data(gcov_filename, covdata, options)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 294, in process_gcov_json_data
    apply_all_exclusions(file_cov, lines=encoded_source_lines, options=options)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\exclusions\__init__.py", line 109, in apply_all_exclusions
    remove_internal_functions(filecov)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\exclusions\__init__.py", line 136, in remove_internal_functions
    filecov.functions.pop(function.demangled_name)
KeyError: '__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > config::skip_list<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)'
(ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\__main__.py", line 358, in main
    covdata: CovData = gcovr_formats.read_reports(options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\__init__.py", line 85, in read_reports
    covdata = GcovHandler(options).read_report()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\__init__.py", line 215, in read_report
    return read_report(self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 96, in read_report
    with Workers(
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 177, in __exit__
    self.wait()
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 103, in read_report
    contexts = pool.wait()
               ^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 81, in worker
    work(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 566, in process_datafile
    done = run_gcov_and_process_files(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 922, in run_gcov_and_process_files
    process_gcov_json_data(gcov_filename, covdata, options)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 294, in process_gcov_json_data
    apply_all_exclusions(file_cov, lines=encoded_source_lines, options=options)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\exclusions\__init__.py", line 109, in apply_all_exclusions
    remove_internal_functions(filecov)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\exclusions\__init__.py", line 136, in remove_internal_functions
    filecov.functions.pop(function.demangled_name)
KeyError: '__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > config::skip_list<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)'

'__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > config::skip_list<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)'
Error: (ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\__main__.py", line 358, in main
    covdata: CovData = gcovr_formats.read_reports(options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\__init__.py", line 85, in read_reports
    covdata = GcovHandler(options).read_report()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\__init__.py", line 215, in read_report
    return read_report(self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 96, in read_report
    with Workers(
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 177, in __exit__
    self.wait()
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 103, in read_report
    contexts = pool.wait()
               ^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\workers.py", line 81, in worker
    work(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 566, in process_datafile
    done = run_gcov_and_process_files(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 922, in run_gcov_and_process_files
    process_gcov_json_data(gcov_filename, covdata, options)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\formats\gcov\read.py", line 294, in process_gcov_json_data
    apply_all_exclusions(file_cov, lines=encoded_source_lines, options=options)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\exclusions\__init__.py", line 109, in apply_all_exclusions
    remove_internal_functions(filecov)
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\gcovr\exclusions\__init__.py", line 136, in remove_internal_functions
    filecov.functions.pop(function.demangled_name)
KeyError: '__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > config::skip_list<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)'

'__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > config::skip_list<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)'
Error: Process completed with exit code 64.
```

I'm unsure of what changed. Didn't see anything obvious in the release notes.

**Comment by ReenigneArcher** [comment]
Thanks for the quick fix! I will verify it once the next release is made.
