### ISSUE TITLE
KeyError: 'block_ids'

### ISSUE THREAD

**Issue by LordAro** [gcovr/gcovr#995]
# Describe the bug

```
(ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/__main__.py", line 358, in main
    covdata: CovData = gcovr_formats.read_reports(options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/__init__.py", line 85, in read_reports
    covdata = GcovHandler(options).read_report()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/__init__.py", line 215, in read_report
    return read_report(self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 96, in read_report
    with Workers(
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 177, in __exit__
    self.wait()
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 103, in read_report
    contexts = pool.wait()
               ^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 81, in worker
    work(*args, **kwargs)
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 1012, in process_existing_gcov_file
    process_gcov_json_data(filename, covdata, options)
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 239, in process_gcov_json_data
    block_ids=line["block_ids"],
              ~~~~^^^^^^^^^^^^^
KeyError: 'block_ids'

'block_ids'
```

# To Reproduce

1. Produce json coverage gcov from GCC 12.3
2. Run gcovr with it.

# Expected behavior

No crash :)

# Screenshots

# Desktop (please complete the following information)

- OS: Windows / MSYS2
- GCC version: 12.3
- GCOVR version 8.2

# Additional context

JSON format listed in the manual does not mention block_ids.

https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Invoking-Gcov.html

Looks like the attribute is optional for `LineCoverage`, so hopefully the fix is nice and easy (same as #978?)

**Comment by LordAro** [comment]
Oh, same issue for `source_block_id` in branches object. Not optional for `BranchCoverage`, so might be a bigger problem?

**Comment by LordAro** [comment]
Ah, it wasn't clear from the documentation which versions that was (I did spot the version 2 check in the code), and clearly I didn't look at the json objects I had closely enough.

Does there need to be a stronger check for the version? I was using `--gcov-use-existing-files` and maybe that bypasses the existing checks?

**Comment by Spacetown** [comment]
> Ah, it wasn't clear from the documentation which GCC versions supported that version (I did spot the version 2 check in the code), and clearly I didn't look at the json objects I had closely enough.
> 
> Does there need to be a stronger check for the version? I was using `--gcov-use-existing-files` and maybe that bypasses the existing checks?

You're right, this bypasses the check and I forgot to verify the verision when reading the JSON files because in your use case it's not in our hand which version is generated. I'll add a check and try to also add a test for this use case.

**Comment by Spacetown** [comment]
@LordAro Pleas can you check the linked PR and add a review comment?
